;  Assembly code generated by mikroVirtualMachine - V. 5.0.0.3
;  Date/Time: 02/12/2010 14:31:08
;  Info: http://www.mikroe.com


; ADDRESS	OPCODE	ASM
; ----------------------------------------------
$0000	$2804			GOTO	_main
$01BD	$	_delay_22us:
;delays.pbas,17 :: 		sub procedure Delay_22us()
;delays.pbas,18 :: 		Delay_us(22)
$01BD	$3007			MOVLW	7
$01BE	$1303			BCF	STATUS, RP1
$01BF	$1283			BCF	STATUS, RP0
$01C0	$00FA			MOVWF	STACK_10
$01C1	$0BFA			DECFSZ	STACK_10, F
$01C2	$29C1			GOTO	$-1
$01C3	$	delays_L_3:
$01C3	$0008			RETURN
$01AC	$	_div_8x8_u:
$01AC	$1303			BCF	STATUS, RP1
$01AD	$1283			BCF	STATUS, RP0
;math.ppas,88 :: 		
;math.ppas,90 :: 		
$01AE	$01F8			CLRF	STACK_8, F
;math.ppas,91 :: 		
$01AF	$3008			MOVLW	8
;math.ppas,92 :: 		
$01B0	$00FC			MOVWF	STACK_12
;math.ppas,93 :: 		
$01B1	$0D70			RLF	STACK_0, W
;math.ppas,94 :: 		
$01B2	$0DF8			RLF	STACK_8, F
;math.ppas,95 :: 		
$01B3	$0874			MOVF	STACK_4, W
;math.ppas,96 :: 		
$01B4	$02F8			SUBWF	STACK_8, F
;math.ppas,97 :: 		
$01B5	$1803			BTFSC	STATUS, C
;math.ppas,98 :: 		
$01B6	$29B9			GOTO	$+3
;math.ppas,99 :: 		
$01B7	$07F8			ADDWF	STACK_8, F
;math.ppas,100 :: 		
$01B8	$1003			BCF	STATUS, C
;math.ppas,101 :: 		
$01B9	$0DF0			RLF	STACK_0, F
;math.ppas,102 :: 		
$01BA	$0BFC			DECFSZ	STACK_12, F
;math.ppas,103 :: 		
$01BB	$29B1			GOTO	$-10
;math.ppas,104 :: 		
$01BC	$	math_L_2:
;math.ppas,105 :: 		
$01BC	$0008			RETURN
$019A	$	_usart_write:
;USART_c67.ppas,40 :: 		
;USART_c67.ppas,42 :: 		
$019A	$	USART_c67_L_14:
$019A	$1303			BCF	STATUS, RP1
$019B	$1683			BSF	STATUS, RP0
$019C	$0818			MOVF	TXSTA, 0
$019D	$00F1			MOVWF	STACK_1
$019E	$3000			MOVLW	0
$019F	$18F1			BTFSC	STACK_1, 1
$01A0	$3001			MOVLW	1
$01A1	$00F1			MOVWF	STACK_1
$01A2	$0871			MOVF	STACK_1, 0
$01A3	$3A00			XORLW	0
$01A4	$1D03			BTFSS	STATUS, Z
$01A5	$29A8			GOTO	USART_c67_L_15
;USART_c67.ppas,43 :: 		
$01A6	$0000			NOP
$01A7	$299A			GOTO	USART_c67_L_14
$01A8	$	USART_c67_L_15:
;USART_c67.ppas,44 :: 		
$01A8	$1283			BCF	STATUS, RP0
$01A9	$0841			MOVF	FARG_USART_Write, 0
$01AA	$0099			MOVWF	TXREG
$01AB	$	USART_c67_L_12:
;USART_c67.ppas,45 :: 		
$01AB	$0008			RETURN
$00F6	$	_adc_read:
;ADClib_88X.ppas,9 :: 		
;ADClib_88X.ppas,10 :: 		
$00F6	$30C0			MOVLW	192
$00F7	$1303			BCF	STATUS, RP1
$00F8	$1283			BCF	STATUS, RP0
$00F9	$009F			MOVWF	ADCON0
;ADClib_88X.ppas,11 :: 		
$00FA	$083D			MOVF	FARG_Adc_Read, 0
$00FB	$00F0			MOVWF	STACK_0
$00FC	$0DF0			RLF	STACK_0, 1
$00FD	$1070			BCF	STACK_0, 0
$00FE	$0DF0			RLF	STACK_0, 1
$00FF	$1070			BCF	STACK_0, 0
$0100	$0870			MOVF	STACK_0, 0
$0101	$049F			IORWF	ADCON0, 1
;ADClib_88X.ppas,12 :: 		
$0102	$	ADClib_88X_L_1:
$0102	$1683			BSF	STATUS, RP0
$0103	$179F			BSF	ADCON1, 7
$0104	$	ADClib_88X_L_2:
;ADClib_88X.ppas,15 :: 		
$0104	$	ADClib_88X_L_3:
$0104	$1283			BCF	STATUS, RP0
$0105	$141F			BSF	ADCON0, 0
$0106	$	ADClib_88X_L_4:
;ADClib_88X.ppas,18 :: 		
$0106	$21BD			CALL	_delay_22us
;ADClib_88X.ppas,21 :: 		
$0107	$	ADClib_88X_L_5:
$0107	$149F			BSF	ADCON0, 1
$0108	$	ADClib_88X_L_6:
;ADClib_88X.ppas,24 :: 		
$0108	$	ADClib_88X_L_8:
$0108	$081F			MOVF	ADCON0, 0
$0109	$00F2			MOVWF	STACK_2
$010A	$3000			MOVLW	0
$010B	$18F2			BTFSC	STACK_2, 1
$010C	$3001			MOVLW	1
$010D	$00F2			MOVWF	STACK_2
$010E	$0872			MOVF	STACK_2, 0
$010F	$3A00			XORLW	0
$0110	$1D03			BTFSS	STATUS, Z
$0111	$2908			GOTO	ADClib_88X_L_8
;ADClib_88X.ppas,26 :: 		
$0112	$	ADClib_88X_L_9:
;ADClib_88X.ppas,29 :: 		
$0112	$101F			BCF	ADCON0, 0
$0113	$	ADClib_88X_L_13:
;ADClib_88X.ppas,32 :: 		
$0113	$081E			MOVF	ADRESH, 0
$0114	$00F2			MOVWF	STACK_2
$0115	$01F3			CLRF	STACK_2+1
$0116	$0872			MOVF	STACK_2, 0
$0117	$00F3			MOVWF	STACK_2+1
$0118	$01F2			CLRF	STACK_2
$0119	$1683			BSF	STATUS, RP0
$011A	$081E			MOVF	ADRESL, 0
$011B	$0472			IORWF	STACK_2, 0
$011C	$1283			BCF	STATUS, RP0
$011D	$00BE			MOVWF	_adc_read_local_result
$011E	$0873			MOVF	STACK_2+1, 0
$011F	$00BF			MOVWF	_adc_read_local_result+1
$0120	$3000			MOVLW	0
$0121	$04BF			IORWF	_adc_read_local_result+1, 1
$0122	$	ADClib_88X_L_0:
;ADClib_88X.ppas,33 :: 		
$0122	$083E			MOVF	_adc_read_local_result, 0
$0123	$00F0			MOVWF	STACK_0
$0124	$083F			MOVF	_adc_read_local_result+1, 0
$0125	$00F1			MOVWF	STACK_0+1
$0126	$0008			RETURN
$00C4	$	_bytetostr:
;conv.ppas,8 :: 		
;conv.ppas,9 :: 		
$00C4	$3001			MOVLW	1
$00C5	$1303			BCF	STATUS, RP1
$00C6	$1283			BCF	STATUS, RP0
$00C7	$00BF			MOVWF	_bytetostr_local_len
;conv.ppas,10 :: 		
$00C8	$083D			MOVF	FARG_ByteToStr, 0
$00C9	$3C09			SUBLW	9
$00CA	$1803			BTFSC	STATUS, C
$00CB	$28CD			GOTO	conv_L_2
$00CC	$	conv_L_1:
;conv.ppas,11 :: 		
$00CC	$0ABF			INCF	_bytetostr_local_len, 1
$00CD	$	conv_L_2:
$00CD	$	conv_L_3:
;conv.ppas,12 :: 		
$00CD	$083D			MOVF	FARG_ByteToStr, 0
$00CE	$3C63			SUBLW	99
$00CF	$1803			BTFSC	STATUS, C
$00D0	$28D2			GOTO	conv_L_5
$00D1	$	conv_L_4:
;conv.ppas,13 :: 		
$00D1	$0ABF			INCF	_bytetostr_local_len, 1
$00D2	$	conv_L_5:
$00D2	$	conv_L_6:
;conv.ppas,14 :: 		
$00D2	$083E			MOVF	FARG_ByteToStr+1, 0
$00D3	$0084			MOVWF	FSR
$00D4	$3020			MOVLW	32
$00D5	$0080			MOVWF	INDF
$00D6	$0A84			INCF	FSR, 1
$00D7	$0080			MOVWF	INDF
$00D8	$0A84			INCF	FSR, 1
$00D9	$0080			MOVWF	INDF
$00DA	$0A84			INCF	FSR, 1
$00DB	$0180			CLRF	INDF
;conv.ppas,15 :: 		
$00DC	$0384			DECF	FSR, 1
;conv.ppas,17 :: 		
$00DD	$	conv_L_9:
$00DD	$083F			MOVF	_bytetostr_local_len, 0
$00DE	$3C00			SUBLW	0
$00DF	$1803			BTFSC	STATUS, C
$00E0	$28F5			GOTO	conv_L_10
;conv.ppas,19 :: 		
$00E1	$300A			MOVLW	10
$00E2	$00F4			MOVWF	STACK_4
$00E3	$083D			MOVF	FARG_ByteToStr, 0
$00E4	$00F0			MOVWF	STACK_0
$00E5	$21AC			CALL	_div_8x8_u
$00E6	$0878			MOVF	STACK_8, 0
$00E7	$00F0			MOVWF	STACK_0
$00E8	$3030			MOVLW	48
$00E9	$0770			ADDWF	STACK_0, 0
$00EA	$0080			MOVWF	INDF
;conv.ppas,20 :: 		
;conv.ppas,21 :: 		
$00EB	$0384			DECF	FSR, 1
;conv.ppas,22 :: 		
$00EC	$300A			MOVLW	10
$00ED	$00F4			MOVWF	STACK_4
$00EE	$083D			MOVF	FARG_ByteToStr, 0
$00EF	$00F0			MOVWF	STACK_0
$00F0	$21AC			CALL	_div_8x8_u
$00F1	$0870			MOVF	STACK_0, 0
$00F2	$00BD			MOVWF	FARG_ByteToStr
;conv.ppas,23 :: 		
$00F3	$03BF			DECF	_bytetostr_local_len, 1
;conv.ppas,24 :: 		
$00F4	$28DD			GOTO	conv_L_9
$00F5	$	conv_L_10:
$00F5	$	conv_L_0:
;conv.ppas,26 :: 		
$00F5	$0008			RETURN
$016F	$	_usart_write_text:
;USART_c67.ppas,121 :: 		
;USART_c67.ppas,122 :: 		
$016F	$1303			BCF	STATUS, RP1
$0170	$1283			BCF	STATUS, RP0
$0171	$01BE			CLRF	_usart_write_text_local_i, 1
;USART_c67.ppas,123 :: 		
$0172	$083D			MOVF	FARG_Usart_Write_Text, 0
$0173	$0084			MOVWF	FSR
$0174	$0800			MOVF	INDF, 0
$0175	$00BF			MOVWF	_usart_write_text_local_data
;USART_c67.ppas,124 :: 		
$0176	$	USART_c67_L_47:
$0176	$083F			MOVF	_usart_write_text_local_data, 0
$0177	$3A00			XORLW	0
$0178	$1903			BTFSC	STATUS, Z
$0179	$2984			GOTO	USART_c67_L_48
;USART_c67.ppas,126 :: 		
$017A	$083F			MOVF	_usart_write_text_local_data, 0
$017B	$00C1			MOVWF	FARG_USART_Write
$017C	$219A			CALL	_usart_write
;USART_c67.ppas,127 :: 		
$017D	$0ABE			INCF	_usart_write_text_local_i, 1
;USART_c67.ppas,128 :: 		
$017E	$083E			MOVF	_usart_write_text_local_i, 0
$017F	$073D			ADDWF	FARG_Usart_Write_Text, 0
$0180	$0084			MOVWF	FSR
$0181	$0800			MOVF	INDF, 0
$0182	$00BF			MOVWF	_usart_write_text_local_data
;USART_c67.ppas,129 :: 		
$0183	$2976			GOTO	USART_c67_L_47
$0184	$	USART_c67_L_48:
$0184	$	USART_c67_L_45:
;USART_c67.ppas,130 :: 		
$0184	$0008			RETURN
$0185	$	_usart_init:
;USART_c67.ppas,22 :: 		
;USART_c67.ppas,24 :: 		
$0185	$	USART_c67_L_1:
$0185	$1303			BCF	STATUS, RP1
$0186	$1683			BSF	STATUS, RP0
$0187	$1698			BSF	TXSTA, 5
$0188	$	USART_c67_L_2:
;USART_c67.ppas,25 :: 		
$0188	$3090			MOVLW	144
$0189	$1283			BCF	STATUS, RP0
$018A	$0098			MOVWF	RCSTA
;USART_c67.ppas,31 :: 		
$018B	$	USART_c67_L_3:
$018B	$1683			BSF	STATUS, RP0
$018C	$1787			BSF	TRISC, 7
$018D	$	USART_c67_L_4:
;USART_c67.ppas,32 :: 		
$018D	$1307			BCF	TRISC, 6
$018E	$	USART_c67_L_6:
;USART_c67.ppas,35 :: 		
$018E	$	USART_c67_L_8:
$018E	$1283			BCF	STATUS, RP0
$018F	$080C			MOVF	PIR1, 0
$0190	$00F1			MOVWF	STACK_1
$0191	$3000			MOVLW	0
$0192	$1AF1			BTFSC	STACK_1, 5
$0193	$3001			MOVLW	1
$0194	$00F1			MOVWF	STACK_1
$0195	$0871			MOVF	STACK_1, 0
$0196	$3A01			XORLW	1
$0197	$1903			BTFSC	STATUS, Z
$0198	$298E			GOTO	USART_c67_L_8
;USART_c67.ppas,36 :: 		
$0199	$	USART_c67_L_9:
$0199	$	USART_c67_L_0:
;USART_c67.ppas,37 :: 		
$0199	$0008			RETURN
$0152	$	_div_16x16_u:
$0152	$1303			BCF	STATUS, RP1
$0153	$1283			BCF	STATUS, RP0
;math.ppas,108 :: 		
;math.ppas,110 :: 		
$0154	$01F8			CLRF	STACK_8
;math.ppas,111 :: 		
$0155	$01F9			CLRF	STACK_9
;math.ppas,112 :: 		
$0156	$3010			MOVLW	16
;math.ppas,113 :: 		
$0157	$00FC			MOVWF	STACK_12
;math.ppas,114 :: 		
$0158	$0D71			RLF	STACK_1, W
;math.ppas,115 :: 		
$0159	$0DF8			RLF	STACK_8, F
;math.ppas,116 :: 		
$015A	$0DF9			RLF	STACK_9, F
;math.ppas,117 :: 		
$015B	$0874			MOVF	STACK_4, W
;math.ppas,118 :: 		
$015C	$02F8			SUBWF	STACK_8, F
;math.ppas,119 :: 		
$015D	$0875			MOVF	STACK_5, W
;math.ppas,120 :: 		
$015E	$1C03			BTFSS	STATUS, C
;math.ppas,121 :: 		
$015F	$0F75			INCFSZ	STACK_5, W
;math.ppas,122 :: 		
$0160	$02F9			SUBWF	STACK_9, F
;math.ppas,123 :: 		
$0161	$1803			BTFSC	STATUS, C
;math.ppas,124 :: 		
$0162	$296A			GOTO	$+8
;math.ppas,125 :: 		
$0163	$0874			MOVF	STACK_4, W
;math.ppas,126 :: 		
$0164	$07F8			ADDWF	STACK_8, F
;math.ppas,127 :: 		
$0165	$0875			MOVF	STACK_5, W
;math.ppas,128 :: 		
$0166	$1803			BTFSC	STATUS, C
;math.ppas,129 :: 		
$0167	$0F75			INCFSZ	STACK_5, W
;math.ppas,130 :: 		
$0168	$07F9			ADDWF	STACK_9, F
;math.ppas,131 :: 		
$0169	$1003			BCF	STATUS, C
;math.ppas,132 :: 		
$016A	$0DF0			RLF	STACK_0, F
;math.ppas,133 :: 		
$016B	$0DF1			RLF	STACK_1, F
;math.ppas,134 :: 		
$016C	$0BFC			DECFSZ	STACK_12, F
;math.ppas,135 :: 		
$016D	$2958			GOTO	$-21
;math.ppas,136 :: 		
$016E	$	math_L_3:
;math.ppas,137 :: 		
$016E	$0008			RETURN
$0127	$	_mul_16x16_u:
$0127	$1303			BCF	STATUS, RP1
$0128	$1283			BCF	STATUS, RP0
;math.ppas,42 :: 		
;math.ppas,44 :: 		
$0129	$01FB			CLRF	STACK_11
;math.ppas,45 :: 		
$012A	$01FA			CLRF	STACK_10
;math.ppas,46 :: 		
$012B	$01F9			CLRF	STACK_9
;math.ppas,47 :: 		
$012C	$3080			MOVLW	128
;math.ppas,48 :: 		
$012D	$00F8			MOVWF	STACK_8
;math.ppas,49 :: 		
$012E	$0CF1			RRF	STACK_1, F
;math.ppas,50 :: 		
$012F	$0CF0			RRF	STACK_0, F
;math.ppas,51 :: 		
$0130	$1C03			BTFSS	STATUS, C
;math.ppas,52 :: 		
$0131	$293B			GOTO	$+10
;math.ppas,53 :: 		
$0132	$0874			MOVF	STACK_4, W
;math.ppas,54 :: 		
$0133	$07F9			ADDWF	STACK_9, F
;math.ppas,55 :: 		
$0134	$0875			MOVF	STACK_5, W
;math.ppas,56 :: 		
$0135	$1803			BTFSC	STATUS, C
;math.ppas,57 :: 		
$0136	$0F75			INCFSZ	STACK_5, W
;math.ppas,58 :: 		
$0137	$07FA			ADDWF	STACK_10, F
;math.ppas,59 :: 		
$0138	$1803			BTFSC	STATUS, C
;math.ppas,60 :: 		
$0139	$0AFB			INCF	STACK_11, F
;math.ppas,61 :: 		
$013A	$1003			BCF	STATUS, C
;math.ppas,62 :: 		
$013B	$1FF0			BTFSS	STACK_0, 7
;math.ppas,63 :: 		
$013C	$2943			GOTO	$+7
;math.ppas,64 :: 		
$013D	$0874			MOVF	STACK_4, W
;math.ppas,65 :: 		
$013E	$07FA			ADDWF	STACK_10, F
;math.ppas,66 :: 		
$013F	$0875			MOVF	STACK_5, W
;math.ppas,67 :: 		
$0140	$1803			BTFSC	STATUS, C
;math.ppas,68 :: 		
$0141	$0F75			INCFSZ	STACK_5, W
;math.ppas,69 :: 		
$0142	$07FB			ADDWF	STACK_11, F
;math.ppas,70 :: 		
$0143	$0CFB			RRF	STACK_11, F
;math.ppas,71 :: 		
$0144	$0CFA			RRF	STACK_10, F
;math.ppas,72 :: 		
$0145	$0CF9			RRF	STACK_9, F
;math.ppas,73 :: 		
$0146	$0CF8			RRF	STACK_8, F
;math.ppas,74 :: 		
$0147	$1C03			BTFSS	STATUS, C
;math.ppas,75 :: 		
$0148	$292E			GOTO	$-26
;math.ppas,76 :: 		
$0149	$087B			MOVF	STACK_11, W
;math.ppas,77 :: 		
$014A	$00F3			MOVWF	STACK_3
;math.ppas,78 :: 		
$014B	$087A			MOVF	STACK_10, W
;math.ppas,79 :: 		
$014C	$00F2			MOVWF	STACK_2
;math.ppas,80 :: 		
$014D	$0879			MOVF	STACK_9, W
;math.ppas,81 :: 		
$014E	$00F1			MOVWF	STACK_1
;math.ppas,82 :: 		
$014F	$0878			MOVF	STACK_8, W
;math.ppas,83 :: 		
$0150	$00F0			MOVWF	STACK_0
;math.ppas,84 :: 		
$0151	$	math_L_1:
;math.ppas,85 :: 		
$0151	$0008			RETURN
$0004	$	_main:
;Codigo_Termocupla_LM35.pbas,7 :: 		main:
$0004	$	_main_main:
;Codigo_Termocupla_LM35.pbas,8 :: 		OPTION_REG=%10000000 ' Configuracion de Puertos analogicos / digitales AN0 - AN13
$0004	$3080			MOVLW	128
$0005	$1303			BCF	STATUS, RP1
$0006	$1683			BSF	STATUS, RP0
$0007	$0081			MOVWF	OPTION_REG
;Codigo_Termocupla_LM35.pbas,9 :: 		ANSEL =  %00000000           'REGISTRO CONFIG. O DIGITAL, 1 ANALOGICO
$0008	$1703			BSF	STATUS, RP1
$0009	$0188			CLRF	ANSEL, 1
;Codigo_Termocupla_LM35.pbas,10 :: 		ANSELH = %00001010           'REGISTRO CONFIG. O DIGITAL, 1 ANALOGICO
$000A	$300A			MOVLW	10
$000B	$0089			MOVWF	ANSELH
;Codigo_Termocupla_LM35.pbas,13 :: 		trisa  = %00000000           ' Configuracion IN/OUT PORTA
$000C	$1303			BCF	STATUS, RP1
$000D	$0185			CLRF	TRISA, 1
;Codigo_Termocupla_LM35.pbas,14 :: 		trisb  = %00011000           ' Configuracion IN/OUT PORTB
$000E	$3018			MOVLW	24
$000F	$0086			MOVWF	TRISB
;Codigo_Termocupla_LM35.pbas,15 :: 		trisc  = %10000000           ' Configuracion IN/OUT PORTC
$0010	$3080			MOVLW	128
$0011	$0087			MOVWF	TRISC
;Codigo_Termocupla_LM35.pbas,19 :: 		PORTA  = %00000000           ' Inicializacion PORTA
$0012	$1283			BCF	STATUS, RP0
$0013	$0185			CLRF	PORTA, 1
;Codigo_Termocupla_LM35.pbas,20 :: 		PORTB  = %00000000           ' Inicializacion PORTC
$0014	$0186			CLRF	PORTB, 1
;Codigo_Termocupla_LM35.pbas,21 :: 		PORTC  = %00000000           ' Inicializacion PORTC
$0015	$0187			CLRF	PORTC, 1
;Codigo_Termocupla_LM35.pbas,23 :: 		muestras=0
$0016	$01A0			CLRF	_muestras, 1
;Codigo_Termocupla_LM35.pbas,24 :: 		temp_prom_term =0
$0017	$01A1			CLRF	_temp_prom_term
$0018	$01A2			CLRF	_temp_prom_term+1
;Codigo_Termocupla_LM35.pbas,25 :: 		temp_prom_LM35=0
$0019	$01A3			CLRF	_temp_prom_lm35
$001A	$01A4			CLRF	_temp_prom_lm35+1
;Codigo_Termocupla_LM35.pbas,26 :: 		temp_term=0
$001B	$01A5			CLRF	_temp_term
$001C	$01A6			CLRF	_temp_term+1
;Codigo_Termocupla_LM35.pbas,27 :: 		temp_LM35=0
$001D	$01A7			CLRF	_temp_lm35
$001E	$01A8			CLRF	_temp_lm35+1
;Codigo_Termocupla_LM35.pbas,28 :: 		temp_term_grad=0
$001F	$01A9			CLRF	_temp_term_grad, 1
;Codigo_Termocupla_LM35.pbas,29 :: 		temp_LM35_grad=0
$0020	$01AA			CLRF	_temp_lm35_grad, 1
;Codigo_Termocupla_LM35.pbas,30 :: 		USART_Init(9600)
$0021	$3019			MOVLW	25
$0022	$1683			BSF	STATUS, RP0
$0023	$0099			MOVWF	SPBRG
$0024	$1518			BSF	TXSTA, BRGH
$0025	$2185			CALL	_usart_init
;Codigo_Termocupla_LM35.pbas,31 :: 		Delay_ms(100)
$0026	$3082			MOVLW	130
$0027	$00FB			MOVWF	STACK_11
$0028	$30FF			MOVLW	255
$0029	$00FA			MOVWF	STACK_10
$002A	$0BFB			DECFSZ	STACK_11, F
$002B	$282D			GOTO	$+2
$002C	$2830			GOTO	$+4
$002D	$0BFA			DECFSZ	STACK_10, F
$002E	$282D			GOTO	$-1
$002F	$282A			GOTO	$-5
$0030	$3087			MOVLW	135
$0031	$00FA			MOVWF	STACK_10
$0032	$0BFA			DECFSZ	STACK_10, F
$0033	$2832			GOTO	$-1
$0034	$0000			NOP
;Codigo_Termocupla_LM35.pbas,34 :: 		while true
$0035	$	Codigo_Termocupla_LM35_L_2:
;Codigo_Termocupla_LM35.pbas,35 :: 		do
$0035	$	Codigo_Termocupla_LM35_L_6:
;Codigo_Termocupla_LM35.pbas,37 :: 		analog_LM35= Adc_Read(9)
$0035	$3009			MOVLW	9
$0036	$00BD			MOVWF	FARG_Adc_Read
$0037	$20F6			CALL	_adc_read
$0038	$0870			MOVF	STACK_0, 0
$0039	$00AB			MOVWF	_analog_lm35
$003A	$0871			MOVF	STACK_0+1, 0
$003B	$00AC			MOVWF	_analog_lm35+1
;Codigo_Termocupla_LM35.pbas,38 :: 		analog_termocupla = Adc_Read(11)
$003C	$300B			MOVLW	11
$003D	$00BD			MOVWF	FARG_Adc_Read
$003E	$20F6			CALL	_adc_read
$003F	$0870			MOVF	STACK_0, 0
$0040	$00AD			MOVWF	_analog_termocupla
$0041	$0871			MOVF	STACK_0+1, 0
$0042	$00AE			MOVWF	_analog_termocupla+1
;Codigo_Termocupla_LM35.pbas,39 :: 		inc(muestras)
$0043	$0AA0			INCF	_muestras, 1
;Codigo_Termocupla_LM35.pbas,40 :: 		Delay_ms(1)
$0044	$3002			MOVLW	2
$0045	$00FB			MOVWF	STACK_11
$0046	$30FF			MOVLW	255
$0047	$00FA			MOVWF	STACK_10
$0048	$0BFB			DECFSZ	STACK_11, F
$0049	$284B			GOTO	$+2
$004A	$284E			GOTO	$+4
$004B	$0BFA			DECFSZ	STACK_10, F
$004C	$284B			GOTO	$-1
$004D	$2848			GOTO	$-5
$004E	$304A			MOVLW	74
$004F	$00FA			MOVWF	STACK_10
$0050	$0BFA			DECFSZ	STACK_10, F
$0051	$2850			GOTO	$-1
;Codigo_Termocupla_LM35.pbas,41 :: 		temp_term= temp_term + analog_termocupla
$0052	$0870			MOVF	STACK_0, 0
$0053	$07A5			ADDWF	_temp_term, 1
$0054	$0871			MOVF	STACK_0+1, 0
$0055	$1803			BTFSC	STATUS, C
$0056	$3F01			ADDLW	1
$0057	$07A6			ADDWF	_temp_term+1, 1
;Codigo_Termocupla_LM35.pbas,42 :: 		temp_LM35= temp_LM35 + analog_LM35
$0058	$082B			MOVF	_analog_lm35, 0
$0059	$07A7			ADDWF	_temp_lm35, 1
$005A	$082C			MOVF	_analog_lm35+1, 0
$005B	$1803			BTFSC	STATUS, C
$005C	$3F01			ADDLW	1
$005D	$07A8			ADDWF	_temp_lm35+1, 1
;Codigo_Termocupla_LM35.pbas,44 :: 		loop until (muestras >=200)
$005E	$	Codigo_Termocupla_LM35_L_7:
$005E	$30C8			MOVLW	200
$005F	$0220			SUBWF	_muestras, 0
$0060	$1C03			BTFSS	STATUS, C
$0061	$2863			GOTO	Codigo_Termocupla_LM35_L_9
$0062	$	Codigo_Termocupla_LM35_L_10:
$0062	$2864			GOTO	Codigo_Termocupla_LM35_L_8
$0063	$	Codigo_Termocupla_LM35_L_9:
$0063	$2835			GOTO	Codigo_Termocupla_LM35_L_6
$0064	$	Codigo_Termocupla_LM35_L_8:
;Codigo_Termocupla_LM35.pbas,47 :: 		temp_prom_LM35 = (temp_LM35 /200)
$0064	$30C8			MOVLW	200
$0065	$00F4			MOVWF	STACK_4
$0066	$01F5			CLRF	STACK_4+1
$0067	$0827			MOVF	_temp_lm35, 0
$0068	$00F0			MOVWF	STACK_0
$0069	$0828			MOVF	_temp_lm35+1, 0
$006A	$00F1			MOVWF	STACK_0+1
$006B	$2152			CALL	_div_16x16_u
$006C	$0870			MOVF	STACK_0, 0
$006D	$00BB			MOVWF	FLOC_main+2
$006E	$0871			MOVF	STACK_0+1, 0
$006F	$00BC			MOVWF	FLOC_main+3
$0070	$083B			MOVF	FLOC_main+2, 0
$0071	$00A3			MOVWF	_temp_prom_lm35
$0072	$083C			MOVF	FLOC_main+3, 0
$0073	$00A4			MOVWF	_temp_prom_lm35+1
;Codigo_Termocupla_LM35.pbas,48 :: 		temp_prom_term = (temp_term /200)
$0074	$30C8			MOVLW	200
$0075	$00F4			MOVWF	STACK_4
$0076	$01F5			CLRF	STACK_4+1
$0077	$0825			MOVF	_temp_term, 0
$0078	$00F0			MOVWF	STACK_0
$0079	$0826			MOVF	_temp_term+1, 0
$007A	$00F1			MOVWF	STACK_0+1
$007B	$2152			CALL	_div_16x16_u
$007C	$0870			MOVF	STACK_0, 0
$007D	$00B9			MOVWF	FLOC_main+0
$007E	$0871			MOVF	STACK_0+1, 0
$007F	$00BA			MOVWF	FLOC_main+1
$0080	$0839			MOVF	FLOC_main+0, 0
$0081	$00A1			MOVWF	_temp_prom_term
$0082	$083A			MOVF	FLOC_main+1, 0
$0083	$00A2			MOVWF	_temp_prom_term+1
;Codigo_Termocupla_LM35.pbas,50 :: 		temp_LM35_grad=(temp_prom_LM35*100/230)
$0084	$083B			MOVF	FLOC_main+2, 0
$0085	$00F0			MOVWF	STACK_0
$0086	$083C			MOVF	FLOC_main+3, 0
$0087	$00F1			MOVWF	STACK_0+1
$0088	$3064			MOVLW	100
$0089	$00F4			MOVWF	STACK_4
$008A	$01F5			CLRF	STACK_4+1
$008B	$2127			CALL	_mul_16x16_u
$008C	$30E6			MOVLW	230
$008D	$00F4			MOVWF	STACK_4
$008E	$01F5			CLRF	STACK_4+1
$008F	$2152			CALL	_div_16x16_u
$0090	$0870			MOVF	STACK_0, 0
$0091	$00AA			MOVWF	_temp_lm35_grad
;Codigo_Termocupla_LM35.pbas,51 :: 		temp_term_grad = temp_prom_term + 16
$0092	$3010			MOVLW	16
$0093	$0739			ADDWF	FLOC_main+0, 0
$0094	$00F0			MOVWF	STACK_0
$0095	$083A			MOVF	FLOC_main+1, 0
$0096	$1803			BTFSC	STATUS, C
$0097	$3F01			ADDLW	1
$0098	$00F1			MOVWF	STACK_0+1
$0099	$0870			MOVF	STACK_0, 0
$009A	$00A9			MOVWF	_temp_term_grad
;Codigo_Termocupla_LM35.pbas,53 :: 		ByteToStr(temp_term_grad ,tx_term)
$009B	$0870			MOVF	STACK_0, 0
$009C	$00BD			MOVWF	FARG_ByteToStr
$009D	$302F			MOVLW	_tx_term
$009E	$00BE			MOVWF	FARG_ByteToStr+1
$009F	$20C4			CALL	_bytetostr
;Codigo_Termocupla_LM35.pbas,54 :: 		ByteToStr (temp_LM35_grad ,tx_LM35)
$00A0	$082A			MOVF	_temp_lm35_grad, 0
$00A1	$00BD			MOVWF	FARG_ByteToStr
$00A2	$3034			MOVLW	_tx_lm35
$00A3	$00BE			MOVWF	FARG_ByteToStr+1
$00A4	$20C4			CALL	_bytetostr
;Codigo_Termocupla_LM35.pbas,56 :: 		USART_Write(116)
$00A5	$3074			MOVLW	116
$00A6	$00C1			MOVWF	FARG_USART_Write
$00A7	$219A			CALL	_usart_write
;Codigo_Termocupla_LM35.pbas,57 :: 		Usart_Write_Text(tx_term)
$00A8	$302F			MOVLW	_tx_term
$00A9	$00BD			MOVWF	FARG_Usart_Write_Text
$00AA	$216F			CALL	_usart_write_text
;Codigo_Termocupla_LM35.pbas,58 :: 		USART_Write (102)
$00AB	$3066			MOVLW	102
$00AC	$00C1			MOVWF	FARG_USART_Write
$00AD	$219A			CALL	_usart_write
;Codigo_Termocupla_LM35.pbas,59 :: 		Usart_Write_Text(tx_LM35)
$00AE	$3034			MOVLW	_tx_lm35
$00AF	$00BD			MOVWF	FARG_Usart_Write_Text
$00B0	$216F			CALL	_usart_write_text
;Codigo_Termocupla_LM35.pbas,60 :: 		USART_Write(10)
$00B1	$300A			MOVLW	10
$00B2	$00C1			MOVWF	FARG_USART_Write
$00B3	$219A			CALL	_usart_write
;Codigo_Termocupla_LM35.pbas,61 :: 		USART_Write(13)
$00B4	$300D			MOVLW	13
$00B5	$00C1			MOVWF	FARG_USART_Write
$00B6	$219A			CALL	_usart_write
;Codigo_Termocupla_LM35.pbas,63 :: 		muestras=0
$00B7	$01A0			CLRF	_muestras, 1
;Codigo_Termocupla_LM35.pbas,64 :: 		temp_LM35=0
$00B8	$01A7			CLRF	_temp_lm35
$00B9	$01A8			CLRF	_temp_lm35+1
;Codigo_Termocupla_LM35.pbas,65 :: 		temp_term=0
$00BA	$01A5			CLRF	_temp_term
$00BB	$01A6			CLRF	_temp_term+1
;Codigo_Termocupla_LM35.pbas,66 :: 		temp_prom_LM35=0
$00BC	$01A3			CLRF	_temp_prom_lm35
$00BD	$01A4			CLRF	_temp_prom_lm35+1
;Codigo_Termocupla_LM35.pbas,67 :: 		temp_prom_term=0
$00BE	$01A1			CLRF	_temp_prom_term
$00BF	$01A2			CLRF	_temp_prom_term+1
;Codigo_Termocupla_LM35.pbas,68 :: 		temp_LM35_grad=0
$00C0	$01AA			CLRF	_temp_lm35_grad, 1
;Codigo_Termocupla_LM35.pbas,69 :: 		temp_term_grad =0
$00C1	$01A9			CLRF	_temp_term_grad, 1
$00C2	$2835			GOTO	Codigo_Termocupla_LM35_L_2
;Codigo_Termocupla_LM35.pbas,72 :: 		wend
$00C3	$28C3			GOTO	$
