;  Assembly code generated by mikroVirtualMachine - V. 5.0.0.3
;  Date/Time: 18/01/2011 13:56:49
;  Info: http://www.mikroe.com


; ADDRESS	OPCODE	ASM
; ----------------------------------------------
$0000	$2890			GOTO	_main
$056D	$	_usart_data_ready:
;USART_c67.ppas,48 :: 		
;USART_c67.ppas,50 :: 		
$056D	$1303			BCF	STATUS, RP1
$056E	$1283			BCF	STATUS, RP0
$056F	$080C			MOVF	PIR1, 0
$0570	$00F1			MOVWF	STACK_1
$0571	$3000			MOVLW	0
$0572	$1AF1			BTFSC	STACK_1, 5
$0573	$3001			MOVLW	1
$0574	$00F1			MOVWF	STACK_1
$0575	$0871			MOVF	STACK_1, 0
$0576	$00BC			MOVWF	_usart_data_ready_local_result
$0577	$	USART_c67_L_18:
;USART_c67.ppas,51 :: 		
$0577	$083C			MOVF	_usart_data_ready_local_result, 0
$0578	$00F0			MOVWF	STACK_0
$0579	$0008			RETURN
$0537	$	_usart_read:
;USART_c67.ppas,54 :: 		
;USART_c67.ppas,55 :: 		
$0537	$1303			BCF	STATUS, RP1
$0538	$1283			BCF	STATUS, RP0
$0539	$081A			MOVF	RCREG, 0
$053A	$00BC			MOVWF	_usart_read_local_result
;USART_c67.ppas,61 :: 		
$053B	$0818			MOVF	RCSTA, 0
$053C	$00F1			MOVWF	STACK_1
$053D	$3000			MOVLW	0
$053E	$18F1			BTFSC	STACK_1, 1
$053F	$3001			MOVLW	1
$0540	$00F1			MOVWF	STACK_1
$0541	$0871			MOVF	STACK_1, 0
$0542	$3A01			XORLW	1
$0543	$1D03			BTFSS	STATUS, Z
$0544	$2D47			GOTO	USART_c67_L_21
$0545	$	USART_c67_L_20:
;USART_c67.ppas,63 :: 		
$0545	$1218			BCF	RCSTA, 4
$0546	$	USART_c67_L_24:
;USART_c67.ppas,64 :: 		
$0546	$	USART_c67_L_25:
$0546	$1618			BSF	RCSTA, 4
$0547	$	USART_c67_L_26:
;USART_c67.ppas,65 :: 		
$0547	$	USART_c67_L_21:
$0547	$	USART_c67_L_22:
$0547	$	USART_c67_L_19:
;USART_c67.ppas,66 :: 		
$0547	$083C			MOVF	_usart_read_local_result, 0
$0548	$00F0			MOVWF	STACK_0
$0549	$0008			RETURN
$0004	$	_interrupt:
$0004	$00FF			MOVWF	STACK_15
$0005	$0E03			SWAPF	STATUS, 0
$0006	$0183			CLRF	STATUS
$0007	$00BA			MOVWF	?saveSTATUS
$0008	$0804			MOVF	FSR, 0
$0009	$00B9			MOVWF	?saveFSR
$000A	$080A			MOVF	PCLATH, 0
$000B	$00BB			MOVWF	?savePCLATH
$000C	$018A			CLRF	PCLATH
$000D	$0872			MOVF	STACK_2, 0
$000E	$00DE			MOVWF	STSAVED_2
$000F	$0871			MOVF	STACK_1, 0
$0010	$00DD			MOVWF	STSAVED_1
$0011	$0870			MOVF	STACK_0, 0
$0012	$00DC			MOVWF	STSAVED_0
;CodigoIncubadora.pbas,7 :: 		sub procedure interrupt()
;CodigoIncubadora.pbas,9 :: 		if(PIR1.RCIF=1)then
$0013	$3000			MOVLW	0
$0014	$1A8C			BTFSC	PIR1, 5
$0015	$3001			MOVLW	1
$0016	$00F2			MOVWF	STACK_2
$0017	$0872			MOVF	STACK_2, 0
$0018	$3A01			XORLW	1
$0019	$1D03			BTFSS	STATUS, Z
$001A	$2826			GOTO	CodigoIncubadora_L_2
$001B	$	CodigoIncubadora_L_1:
;CodigoIncubadora.pbas,10 :: 		if Usart_Data_Ready = 1 then
$001B	$256D			CALL	_usart_data_ready
$001C	$0870			MOVF	STACK_0, 0
$001D	$3A01			XORLW	1
$001E	$1D03			BTFSS	STATUS, Z
$001F	$2823			GOTO	CodigoIncubadora_L_5
$0020	$	CodigoIncubadora_L_4:
;CodigoIncubadora.pbas,11 :: 		set_temp = Usart_Read
$0020	$2537			CALL	_usart_read
$0021	$0870			MOVF	STACK_0, 0
$0022	$00A0			MOVWF	_set_temp
$0023	$	CodigoIncubadora_L_5:
;CodigoIncubadora.pbas,12 :: 		end if
$0023	$	CodigoIncubadora_L_6:
;CodigoIncubadora.pbas,13 :: 		PIR1.RCIF=0   ' Si el dato a llegado limpio la bandera de recepcion
$0023	$128C			BCF	PIR1, 5
$0024	$	CodigoIncubadora_L_8:
;CodigoIncubadora.pbas,14 :: 		PIE1.RCIE=1   ' Habilitar nuevamente la interrupcion por USART
$0024	$	CodigoIncubadora_L_9:
$0024	$1683			BSF	STATUS, RP0
$0025	$168C			BSF	PIE1, 5
$0026	$	CodigoIncubadora_L_10:
$0026	$	CodigoIncubadora_L_2:
;CodigoIncubadora.pbas,15 :: 		end if
$0026	$	CodigoIncubadora_L_3:
;CodigoIncubadora.pbas,17 :: 		if(INTCON.INTF=1)then
$0026	$1303			BCF	STATUS, RP1
$0027	$1683			BSF	STATUS, RP0
$0028	$3000			MOVLW	0
$0029	$188B			BTFSC	INTCON, 1
$002A	$3001			MOVLW	1
$002B	$00F2			MOVWF	STACK_2
$002C	$0872			MOVF	STACK_2, 0
$002D	$3A01			XORLW	1
$002E	$1D03			BTFSS	STATUS, Z
$002F	$2874			GOTO	CodigoIncubadora_L_12
$0030	$	CodigoIncubadora_L_11:
;CodigoIncubadora.pbas,18 :: 		if(intensidad > 0)then
$0030	$1283			BCF	STATUS, RP0
$0031	$0821			MOVF	_intensidad, 0
$0032	$3C00			SUBLW	0
$0033	$1803			BTFSC	STATUS, C
$0034	$2871			GOTO	CodigoIncubadora_L_15
$0035	$	CodigoIncubadora_L_14:
;CodigoIncubadora.pbas,19 :: 		PORTB.5=0
$0035	$1286			BCF	PORTB, 5
$0036	$	CodigoIncubadora_L_18:
;CodigoIncubadora.pbas,22 :: 		case 1
$0036	$	CodigoIncubadora_L_21:
$0036	$0821			MOVF	_intensidad, 0
$0037	$3A01			XORLW	1
$0038	$1D03			BTFSS	STATUS, Z
$0039	$283D			GOTO	CodigoIncubadora_L_22
$003A	$	CodigoIncubadora_L_20:
;CodigoIncubadora.pbas,23 :: 		TMR0=240          ''(4/FOSC)*PRESCALADOR*(256-TMR0)=RETARDO
$003A	$30F0			MOVLW	240
$003B	$0081			MOVWF	TMR0
$003C	$286E			GOTO	CodigoIncubadora_L_19
$003D	$	CodigoIncubadora_L_22:
;CodigoIncubadora.pbas,24 :: 		case 2
$003D	$	CodigoIncubadora_L_24:
$003D	$0821			MOVF	_intensidad, 0
$003E	$3A02			XORLW	2
$003F	$1D03			BTFSS	STATUS, Z
$0040	$2844			GOTO	CodigoIncubadora_L_25
$0041	$	CodigoIncubadora_L_23:
;CodigoIncubadora.pbas,25 :: 		TMR0=225
$0041	$30E1			MOVLW	225
$0042	$0081			MOVWF	TMR0
$0043	$286E			GOTO	CodigoIncubadora_L_19
$0044	$	CodigoIncubadora_L_25:
;CodigoIncubadora.pbas,26 :: 		case 3
$0044	$	CodigoIncubadora_L_27:
$0044	$0821			MOVF	_intensidad, 0
$0045	$3A03			XORLW	3
$0046	$1D03			BTFSS	STATUS, Z
$0047	$284B			GOTO	CodigoIncubadora_L_28
$0048	$	CodigoIncubadora_L_26:
;CodigoIncubadora.pbas,27 :: 		TMR0=209
$0048	$30D1			MOVLW	209
$0049	$0081			MOVWF	TMR0
$004A	$286E			GOTO	CodigoIncubadora_L_19
$004B	$	CodigoIncubadora_L_28:
;CodigoIncubadora.pbas,28 :: 		case 4
$004B	$	CodigoIncubadora_L_30:
$004B	$0821			MOVF	_intensidad, 0
$004C	$3A04			XORLW	4
$004D	$1D03			BTFSS	STATUS, Z
$004E	$2852			GOTO	CodigoIncubadora_L_31
$004F	$	CodigoIncubadora_L_29:
;CodigoIncubadora.pbas,29 :: 		TMR0=193
$004F	$30C1			MOVLW	193
$0050	$0081			MOVWF	TMR0
$0051	$286E			GOTO	CodigoIncubadora_L_19
$0052	$	CodigoIncubadora_L_31:
;CodigoIncubadora.pbas,30 :: 		case 5
$0052	$	CodigoIncubadora_L_33:
$0052	$0821			MOVF	_intensidad, 0
$0053	$3A05			XORLW	5
$0054	$1D03			BTFSS	STATUS, Z
$0055	$2859			GOTO	CodigoIncubadora_L_34
$0056	$	CodigoIncubadora_L_32:
;CodigoIncubadora.pbas,31 :: 		TMR0=178
$0056	$30B2			MOVLW	178
$0057	$0081			MOVWF	TMR0
$0058	$286E			GOTO	CodigoIncubadora_L_19
$0059	$	CodigoIncubadora_L_34:
;CodigoIncubadora.pbas,32 :: 		case 6
$0059	$	CodigoIncubadora_L_36:
$0059	$0821			MOVF	_intensidad, 0
$005A	$3A06			XORLW	6
$005B	$1D03			BTFSS	STATUS, Z
$005C	$2860			GOTO	CodigoIncubadora_L_37
$005D	$	CodigoIncubadora_L_35:
;CodigoIncubadora.pbas,33 :: 		TMR0=162
$005D	$30A2			MOVLW	162
$005E	$0081			MOVWF	TMR0
$005F	$286E			GOTO	CodigoIncubadora_L_19
$0060	$	CodigoIncubadora_L_37:
;CodigoIncubadora.pbas,34 :: 		case 7
$0060	$	CodigoIncubadora_L_39:
$0060	$0821			MOVF	_intensidad, 0
$0061	$3A07			XORLW	7
$0062	$1D03			BTFSS	STATUS, Z
$0063	$2867			GOTO	CodigoIncubadora_L_40
$0064	$	CodigoIncubadora_L_38:
;CodigoIncubadora.pbas,35 :: 		TMR0=146
$0064	$3092			MOVLW	146
$0065	$0081			MOVWF	TMR0
$0066	$286E			GOTO	CodigoIncubadora_L_19
$0067	$	CodigoIncubadora_L_40:
;CodigoIncubadora.pbas,36 :: 		case 8
$0067	$	CodigoIncubadora_L_42:
$0067	$0821			MOVF	_intensidad, 0
$0068	$3A08			XORLW	8
$0069	$1D03			BTFSS	STATUS, Z
$006A	$286E			GOTO	CodigoIncubadora_L_43
$006B	$	CodigoIncubadora_L_41:
;CodigoIncubadora.pbas,37 :: 		TMR0=131
$006B	$3083			MOVLW	131
$006C	$0081			MOVWF	TMR0
$006D	$286E			GOTO	CodigoIncubadora_L_19
$006E	$	CodigoIncubadora_L_43:
$006E	$	CodigoIncubadora_L_19:
;CodigoIncubadora.pbas,39 :: 		INTCON.T0IF=0
$006E	$110B			BCF	INTCON, 2
$006F	$	CodigoIncubadora_L_45:
;CodigoIncubadora.pbas,40 :: 		INTCON.T0IE=1
$006F	$	CodigoIncubadora_L_46:
$006F	$168B			BSF	INTCON, 5
$0070	$	CodigoIncubadora_L_47:
$0070	$2872			GOTO	CodigoIncubadora_L_16
;CodigoIncubadora.pbas,41 :: 		else
$0071	$	CodigoIncubadora_L_15:
;CodigoIncubadora.pbas,42 :: 		PORTB.5=1
$0071	$	CodigoIncubadora_L_48:
$0071	$1686			BSF	PORTB, 5
$0072	$	CodigoIncubadora_L_49:
;CodigoIncubadora.pbas,43 :: 		end if
$0072	$	CodigoIncubadora_L_16:
;CodigoIncubadora.pbas,44 :: 		INTCON.INTF=0
$0072	$108B			BCF	INTCON, 1
$0073	$	CodigoIncubadora_L_51:
;CodigoIncubadora.pbas,45 :: 		INTCON.INTE =1
$0073	$	CodigoIncubadora_L_52:
$0073	$160B			BSF	INTCON, 4
$0074	$	CodigoIncubadora_L_53:
$0074	$	CodigoIncubadora_L_12:
;CodigoIncubadora.pbas,47 :: 		end if
$0074	$	CodigoIncubadora_L_13:
;CodigoIncubadora.pbas,49 :: 		if(INTCON.T0IF =1)then
$0074	$1303			BCF	STATUS, RP1
$0075	$1283			BCF	STATUS, RP0
$0076	$3000			MOVLW	0
$0077	$190B			BTFSC	INTCON, 2
$0078	$3001			MOVLW	1
$0079	$00F2			MOVWF	STACK_2
$007A	$0872			MOVF	STACK_2, 0
$007B	$3A01			XORLW	1
$007C	$1D03			BTFSS	STATUS, Z
$007D	$2881			GOTO	CodigoIncubadora_L_55
$007E	$	CodigoIncubadora_L_54:
;CodigoIncubadora.pbas,50 :: 		PORTB.5=1
$007E	$	CodigoIncubadora_L_57:
$007E	$1686			BSF	PORTB, 5
$007F	$	CodigoIncubadora_L_58:
;CodigoIncubadora.pbas,51 :: 		INTCON.T0IF=0
$007F	$110B			BCF	INTCON, 2
$0080	$	CodigoIncubadora_L_60:
;CodigoIncubadora.pbas,52 :: 		INTCON.T0IE=0
$0080	$128B			BCF	INTCON, 5
$0081	$	CodigoIncubadora_L_62:
$0081	$	CodigoIncubadora_L_55:
;CodigoIncubadora.pbas,53 :: 		end if
$0081	$	CodigoIncubadora_L_56:
$0081	$	CodigoIncubadora_L_0:
$0081	$	L_Interrupt_end:
$0081	$085E			MOVF	STSAVED_2, 0
$0082	$00F2			MOVWF	STACK_2
$0083	$085D			MOVF	STSAVED_1, 0
$0084	$00F1			MOVWF	STACK_1
$0085	$085C			MOVF	STSAVED_0, 0
$0086	$00F0			MOVWF	STACK_0
$0087	$083B			MOVF	?savePCLATH, 0
$0088	$008A			MOVWF	PCLATH
$0089	$0839			MOVF	?saveFSR, 0
$008A	$0084			MOVWF	FSR
$008B	$0E3A			SWAPF	?saveSTATUS, 0
$008C	$0083			MOVWF	STATUS
$008D	$0EFF			SWAPF	STACK_15, 1
$008E	$0E7F			SWAPF	STACK_15, 0
$008F	$0009			RETFIE
$0592	$	_delay_1us:
;delays.pbas,9 :: 		sub procedure Delay_1us()
;delays.pbas,10 :: 		Delay_us(1)
$0592	$0000			NOP
$0593	$	delays_L_1:
$0593	$0008			RETURN
$055C	$	_delay_5500us:
;delays.pbas,33 :: 		sub procedure Delay_5500us()
;delays.pbas,34 :: 		Delay_us(5500)
$055C	$3008			MOVLW	8
$055D	$1303			BCF	STATUS, RP1
$055E	$1283			BCF	STATUS, RP0
$055F	$00FB			MOVWF	STACK_11
$0560	$30FF			MOVLW	255
$0561	$00FA			MOVWF	STACK_10
$0562	$0BFB			DECFSZ	STACK_11, F
$0563	$2D65			GOTO	$+2
$0564	$2D68			GOTO	$+4
$0565	$0BFA			DECFSZ	STACK_10, F
$0566	$2D65			GOTO	$-1
$0567	$2D62			GOTO	$-5
$0568	$301E			MOVLW	30
$0569	$00FA			MOVWF	STACK_10
$056A	$0BFA			DECFSZ	STACK_10, F
$056B	$2D6A			GOTO	$-1
$056C	$	delays_L_7:
$056C	$0008			RETURN
$0583	$	_delay_50us:
;delays.pbas,21 :: 		sub procedure Delay_50us()
;delays.pbas,22 :: 		Delay_us(50)
$0583	$3010			MOVLW	16
$0584	$1303			BCF	STATUS, RP1
$0585	$1283			BCF	STATUS, RP0
$0586	$00FA			MOVWF	STACK_10
$0587	$0BFA			DECFSZ	STACK_10, F
$0588	$2D87			GOTO	$-1
$0589	$0000			NOP
$058A	$	delays_L_4:
$058A	$0008			RETURN
$0391	$	_lcd_cmd:
;lcd.ppas,19 :: 		
;lcd.ppas,20 :: 		
$0391	$1303			BCF	STATUS, RP1
$0392	$1283			BCF	STATUS, RP0
$0393	$0822			MOVF	lcd_ctrlport_address, 0
$0394	$0084			MOVWF	FSR
;lcd.ppas,22 :: 		
$0395	$0923			COMF	lcd____menable, W
$0396	$00F0			MOVWF	STACK_0
$0397	$0870			MOVF	STACK_0, 0
$0398	$0580			ANDWF	INDF, 1
;lcd.ppas,23 :: 		
$0399	$0924			COMF	lcd____mrs, W
$039A	$00F0			MOVWF	STACK_0
$039B	$0870			MOVF	STACK_0, 0
$039C	$0580			ANDWF	INDF, 1
;lcd.ppas,25 :: 		
$039D	$0825			MOVF	lcd_dataport_address, 0
$039E	$0084			MOVWF	FSR
;lcd.ppas,26 :: 		
$039F	$0827			MOVF	lcd____mdb6, 0
$03A0	$0426			IORWF	lcd____mdb7, 0
$03A1	$00F0			MOVWF	STACK_0
$03A2	$0828			MOVF	lcd____mdb5, 0
$03A3	$04F0			IORWF	STACK_0, 1
$03A4	$0829			MOVF	lcd____mdb4, 0
$03A5	$04F0			IORWF	STACK_0, 1
$03A6	$09F0			COMF	STACK_0, F
$03A7	$0870			MOVF	STACK_0, 0
$03A8	$0580			ANDWF	INDF, 1
;lcd.ppas,28 :: 		
$03A9	$3000			MOVLW	0
$03AA	$1BDB			BTFSC	FARG_Lcd_Cmd, 7
$03AB	$3001			MOVLW	1
$03AC	$00F1			MOVWF	STACK_1
$03AD	$0871			MOVF	STACK_1, 0
$03AE	$3A01			XORLW	1
$03AF	$1D03			BTFSS	STATUS, Z
$03B0	$2BB3			GOTO	lcd_L_2
$03B1	$	lcd_L_1:
;lcd.ppas,29 :: 		
$03B1	$0826			MOVF	lcd____mdb7, 0
$03B2	$0480			IORWF	INDF, 1
$03B3	$	lcd_L_2:
$03B3	$	lcd_L_3:
;lcd.ppas,30 :: 		
$03B3	$3000			MOVLW	0
$03B4	$1B5B			BTFSC	FARG_Lcd_Cmd, 6
$03B5	$3001			MOVLW	1
$03B6	$00F1			MOVWF	STACK_1
$03B7	$0871			MOVF	STACK_1, 0
$03B8	$3A01			XORLW	1
$03B9	$1D03			BTFSS	STATUS, Z
$03BA	$2BBD			GOTO	lcd_L_5
$03BB	$	lcd_L_4:
;lcd.ppas,31 :: 		
$03BB	$0827			MOVF	lcd____mdb6, 0
$03BC	$0480			IORWF	INDF, 1
$03BD	$	lcd_L_5:
$03BD	$	lcd_L_6:
;lcd.ppas,32 :: 		
$03BD	$3000			MOVLW	0
$03BE	$1ADB			BTFSC	FARG_Lcd_Cmd, 5
$03BF	$3001			MOVLW	1
$03C0	$00F1			MOVWF	STACK_1
$03C1	$0871			MOVF	STACK_1, 0
$03C2	$3A01			XORLW	1
$03C3	$1D03			BTFSS	STATUS, Z
$03C4	$2BC7			GOTO	lcd_L_8
$03C5	$	lcd_L_7:
;lcd.ppas,33 :: 		
$03C5	$0828			MOVF	lcd____mdb5, 0
$03C6	$0480			IORWF	INDF, 1
$03C7	$	lcd_L_8:
$03C7	$	lcd_L_9:
;lcd.ppas,34 :: 		
$03C7	$3000			MOVLW	0
$03C8	$1A5B			BTFSC	FARG_Lcd_Cmd, 4
$03C9	$3001			MOVLW	1
$03CA	$00F1			MOVWF	STACK_1
$03CB	$0871			MOVF	STACK_1, 0
$03CC	$3A01			XORLW	1
$03CD	$1D03			BTFSS	STATUS, Z
$03CE	$2BD1			GOTO	lcd_L_11
$03CF	$	lcd_L_10:
;lcd.ppas,35 :: 		
$03CF	$0829			MOVF	lcd____mdb4, 0
$03D0	$0480			IORWF	INDF, 1
$03D1	$	lcd_L_11:
$03D1	$	lcd_L_12:
;lcd.ppas,37 :: 		
$03D1	$0822			MOVF	lcd_ctrlport_address, 0
$03D2	$0084			MOVWF	FSR
;lcd.ppas,38 :: 		
$03D3	$082A			MOVF	lcd_lcdcmd_status, 0
$03D4	$3A01			XORLW	1
$03D5	$1D03			BTFSS	STATUS, Z
$03D6	$2BDC			GOTO	lcd_L_14
$03D7	$	lcd_L_13:
;lcd.ppas,39 :: 		
$03D7	$0924			COMF	lcd____mrs, W
$03D8	$00F0			MOVWF	STACK_0
$03D9	$0870			MOVF	STACK_0, 0
$03DA	$0580			ANDWF	INDF, 1
$03DB	$2BDE			GOTO	lcd_L_15
;lcd.ppas,40 :: 		
$03DC	$	lcd_L_14:
;lcd.ppas,41 :: 		
$03DC	$0824			MOVF	lcd____mrs, 0
$03DD	$0480			IORWF	INDF, 1
$03DE	$	lcd_L_15:
;lcd.ppas,43 :: 		
$03DE	$0823			MOVF	lcd____menable, 0
$03DF	$0480			IORWF	INDF, 1
;lcd.ppas,44 :: 		
$03E0	$2592			CALL	_delay_1us
;lcd.ppas,45 :: 		
$03E1	$0923			COMF	lcd____menable, W
$03E2	$00F0			MOVWF	STACK_0
$03E3	$0870			MOVF	STACK_0, 0
$03E4	$0580			ANDWF	INDF, 1
;lcd.ppas,47 :: 		
$03E5	$0924			COMF	lcd____mrs, W
$03E6	$00F0			MOVWF	STACK_0
$03E7	$0870			MOVF	STACK_0, 0
$03E8	$0580			ANDWF	INDF, 1
;lcd.ppas,49 :: 		
$03E9	$0825			MOVF	lcd_dataport_address, 0
$03EA	$0084			MOVWF	FSR
;lcd.ppas,50 :: 		
$03EB	$0827			MOVF	lcd____mdb6, 0
$03EC	$0426			IORWF	lcd____mdb7, 0
$03ED	$00F0			MOVWF	STACK_0
$03EE	$0828			MOVF	lcd____mdb5, 0
$03EF	$04F0			IORWF	STACK_0, 1
$03F0	$0829			MOVF	lcd____mdb4, 0
$03F1	$04F0			IORWF	STACK_0, 1
$03F2	$09F0			COMF	STACK_0, F
$03F3	$0870			MOVF	STACK_0, 0
$03F4	$0580			ANDWF	INDF, 1
;lcd.ppas,52 :: 		
$03F5	$3000			MOVLW	0
$03F6	$19DB			BTFSC	FARG_Lcd_Cmd, 3
$03F7	$3001			MOVLW	1
$03F8	$00F1			MOVWF	STACK_1
$03F9	$0871			MOVF	STACK_1, 0
$03FA	$3A01			XORLW	1
$03FB	$1D03			BTFSS	STATUS, Z
$03FC	$2BFF			GOTO	lcd_L_17
$03FD	$	lcd_L_16:
;lcd.ppas,53 :: 		
$03FD	$0826			MOVF	lcd____mdb7, 0
$03FE	$0480			IORWF	INDF, 1
$03FF	$	lcd_L_17:
$03FF	$	lcd_L_18:
;lcd.ppas,54 :: 		
$03FF	$3000			MOVLW	0
$0400	$195B			BTFSC	FARG_Lcd_Cmd, 2
$0401	$3001			MOVLW	1
$0402	$00F1			MOVWF	STACK_1
$0403	$0871			MOVF	STACK_1, 0
$0404	$3A01			XORLW	1
$0405	$1D03			BTFSS	STATUS, Z
$0406	$2C09			GOTO	lcd_L_20
$0407	$	lcd_L_19:
;lcd.ppas,55 :: 		
$0407	$0827			MOVF	lcd____mdb6, 0
$0408	$0480			IORWF	INDF, 1
$0409	$	lcd_L_20:
$0409	$	lcd_L_21:
;lcd.ppas,56 :: 		
$0409	$3000			MOVLW	0
$040A	$18DB			BTFSC	FARG_Lcd_Cmd, 1
$040B	$3001			MOVLW	1
$040C	$00F1			MOVWF	STACK_1
$040D	$0871			MOVF	STACK_1, 0
$040E	$3A01			XORLW	1
$040F	$1D03			BTFSS	STATUS, Z
$0410	$2C13			GOTO	lcd_L_23
$0411	$	lcd_L_22:
;lcd.ppas,57 :: 		
$0411	$0828			MOVF	lcd____mdb5, 0
$0412	$0480			IORWF	INDF, 1
$0413	$	lcd_L_23:
$0413	$	lcd_L_24:
;lcd.ppas,58 :: 		
$0413	$3001			MOVLW	1
$0414	$055B			ANDWF	FARG_Lcd_Cmd, 0
$0415	$00F1			MOVWF	STACK_1
$0416	$0871			MOVF	STACK_1, 0
$0417	$3A01			XORLW	1
$0418	$1D03			BTFSS	STATUS, Z
$0419	$2C1C			GOTO	lcd_L_26
$041A	$	lcd_L_25:
;lcd.ppas,59 :: 		
$041A	$0829			MOVF	lcd____mdb4, 0
$041B	$0480			IORWF	INDF, 1
$041C	$	lcd_L_26:
$041C	$	lcd_L_27:
;lcd.ppas,61 :: 		
$041C	$0822			MOVF	lcd_ctrlport_address, 0
$041D	$0084			MOVWF	FSR
;lcd.ppas,62 :: 		
$041E	$082A			MOVF	lcd_lcdcmd_status, 0
$041F	$3A01			XORLW	1
$0420	$1D03			BTFSS	STATUS, Z
$0421	$2C27			GOTO	lcd_L_29
$0422	$	lcd_L_28:
;lcd.ppas,63 :: 		
$0422	$0924			COMF	lcd____mrs, W
$0423	$00F0			MOVWF	STACK_0
$0424	$0870			MOVF	STACK_0, 0
$0425	$0580			ANDWF	INDF, 1
$0426	$2C29			GOTO	lcd_L_30
;lcd.ppas,64 :: 		
$0427	$	lcd_L_29:
;lcd.ppas,65 :: 		
$0427	$0824			MOVF	lcd____mrs, 0
$0428	$0480			IORWF	INDF, 1
$0429	$	lcd_L_30:
;lcd.ppas,67 :: 		
$0429	$0823			MOVF	lcd____menable, 0
$042A	$0480			IORWF	INDF, 1
;lcd.ppas,68 :: 		
$042B	$2592			CALL	_delay_1us
;lcd.ppas,69 :: 		
$042C	$0923			COMF	lcd____menable, W
$042D	$00F0			MOVWF	STACK_0
$042E	$0870			MOVF	STACK_0, 0
$042F	$0580			ANDWF	INDF, 1
;lcd.ppas,71 :: 		
$0430	$082A			MOVF	lcd_lcdcmd_status, 0
$0431	$3A01			XORLW	1
$0432	$1D03			BTFSS	STATUS, Z
$0433	$2C36			GOTO	lcd_L_32
$0434	$	lcd_L_31:
;lcd.ppas,72 :: 		
$0434	$255C			CALL	_delay_5500us
$0435	$2C37			GOTO	lcd_L_33
;lcd.ppas,73 :: 		
$0436	$	lcd_L_32:
;lcd.ppas,74 :: 		
$0436	$2583			CALL	_delay_50us
$0437	$	lcd_L_33:
$0437	$	lcd_L_0:
;lcd.ppas,75 :: 		
$0437	$0008			RETURN
$057A	$	_lcd_chr_cp:
;lcd.ppas,97 :: 		
;lcd.ppas,98 :: 		
$057A	$1303			BCF	STATUS, RP1
$057B	$1283			BCF	STATUS, RP0
$057C	$01AA			CLRF	lcd_lcdcmd_status, 1
;lcd.ppas,99 :: 		
$057D	$085A			MOVF	FARG_Lcd_Chr_CP, 0
$057E	$00DB			MOVWF	FARG_Lcd_Cmd
$057F	$2391			CALL	_lcd_cmd
;lcd.ppas,100 :: 		
$0580	$3001			MOVLW	1
$0581	$00AA			MOVWF	lcd_lcdcmd_status
$0582	$	lcd_L_48:
;lcd.ppas,101 :: 		
$0582	$0008			RETURN
$058B	$	_delay_22us:
;delays.pbas,17 :: 		sub procedure Delay_22us()
;delays.pbas,18 :: 		Delay_us(22)
$058B	$3007			MOVLW	7
$058C	$1303			BCF	STATUS, RP1
$058D	$1283			BCF	STATUS, RP0
$058E	$00FA			MOVWF	STACK_10
$058F	$0BFA			DECFSZ	STACK_10, F
$0590	$2D8F			GOTO	$-1
$0591	$	delays_L_3:
$0591	$0008			RETURN
$0272	$	_lcd_config:
;lcd.ppas,115 :: 		
;lcd.ppas,116 :: 		
$0272	$255C			CALL	_delay_5500us
;lcd.ppas,117 :: 		
$0273	$255C			CALL	_delay_5500us
;lcd.ppas,118 :: 		
$0274	$255C			CALL	_delay_5500us
;lcd.ppas,120 :: 		
$0275	$0852			MOVF	FARG_Lcd_Config+1, 0
$0276	$00F0			MOVWF	STACK_0
$0277	$3001			MOVLW	1
$0278	$00F4			MOVWF	STACK_4
$0279	$0870			MOVF	STACK_0, 0
$027A	$	L_Lcd_Config_0:
$027A	$1903			BTFSC	STATUS, Z
$027B	$2A80			GOTO	L_Lcd_Config_1
$027C	$0DF4			RLF	STACK_4, 1
$027D	$1074			BCF	STACK_4, 0
$027E	$3FFF			ADDLW	255
$027F	$2A7A			GOTO	L_Lcd_Config_0
$0280	$	L_Lcd_Config_1:
$0280	$0874			MOVF	STACK_4, 0
$0281	$00A6			MOVWF	lcd____mdb7
;lcd.ppas,121 :: 		
$0282	$0853			MOVF	FARG_Lcd_Config+2, 0
$0283	$00F0			MOVWF	STACK_0
$0284	$3001			MOVLW	1
$0285	$00F3			MOVWF	STACK_3
$0286	$0870			MOVF	STACK_0, 0
$0287	$	L_Lcd_Config_2:
$0287	$1903			BTFSC	STATUS, Z
$0288	$2A8D			GOTO	L_Lcd_Config_3
$0289	$0DF3			RLF	STACK_3, 1
$028A	$1073			BCF	STACK_3, 0
$028B	$3FFF			ADDLW	255
$028C	$2A87			GOTO	L_Lcd_Config_2
$028D	$	L_Lcd_Config_3:
$028D	$0873			MOVF	STACK_3, 0
$028E	$00A7			MOVWF	lcd____mdb6
;lcd.ppas,122 :: 		
$028F	$0854			MOVF	FARG_Lcd_Config+3, 0
$0290	$00F0			MOVWF	STACK_0
$0291	$3001			MOVLW	1
$0292	$00F2			MOVWF	STACK_2
$0293	$0870			MOVF	STACK_0, 0
$0294	$	L_Lcd_Config_4:
$0294	$1903			BTFSC	STATUS, Z
$0295	$2A9A			GOTO	L_Lcd_Config_5
$0296	$0DF2			RLF	STACK_2, 1
$0297	$1072			BCF	STACK_2, 0
$0298	$3FFF			ADDLW	255
$0299	$2A94			GOTO	L_Lcd_Config_4
$029A	$	L_Lcd_Config_5:
$029A	$0872			MOVF	STACK_2, 0
$029B	$00A8			MOVWF	lcd____mdb5
;lcd.ppas,123 :: 		
$029C	$0855			MOVF	FARG_Lcd_Config+4, 0
$029D	$00F0			MOVWF	STACK_0
$029E	$3001			MOVLW	1
$029F	$00F1			MOVWF	STACK_1
$02A0	$0870			MOVF	STACK_0, 0
$02A1	$	L_Lcd_Config_6:
$02A1	$1903			BTFSC	STATUS, Z
$02A2	$2AA7			GOTO	L_Lcd_Config_7
$02A3	$0DF1			RLF	STACK_1, 1
$02A4	$1071			BCF	STACK_1, 0
$02A5	$3FFF			ADDLW	255
$02A6	$2AA1			GOTO	L_Lcd_Config_6
$02A7	$	L_Lcd_Config_7:
$02A7	$0871			MOVF	STACK_1, 0
$02A8	$00A9			MOVWF	lcd____mdb4
;lcd.ppas,124 :: 		
$02A9	$0857			MOVF	FARG_Lcd_Config+6, 0
$02AA	$00F0			MOVWF	STACK_0
$02AB	$3001			MOVLW	1
$02AC	$00A4			MOVWF	lcd____mrs
$02AD	$0870			MOVF	STACK_0, 0
$02AE	$	L_Lcd_Config_8:
$02AE	$1903			BTFSC	STATUS, Z
$02AF	$2AB4			GOTO	L_Lcd_Config_9
$02B0	$0DA4			RLF	lcd____mrs, 1
$02B1	$1024			BCF	lcd____mrs, 0
$02B2	$3FFF			ADDLW	255
$02B3	$2AAE			GOTO	L_Lcd_Config_8
$02B4	$	L_Lcd_Config_9:
;lcd.ppas,125 :: 		
$02B4	$0858			MOVF	FARG_Lcd_Config+7, 0
$02B5	$00F0			MOVWF	STACK_0
$02B6	$3001			MOVLW	1
$02B7	$00AB			MOVWF	lcd____mrw
$02B8	$0870			MOVF	STACK_0, 0
$02B9	$	L_Lcd_Config_10:
$02B9	$1903			BTFSC	STATUS, Z
$02BA	$2ABF			GOTO	L_Lcd_Config_11
$02BB	$0DAB			RLF	lcd____mrw, 1
$02BC	$102B			BCF	lcd____mrw, 0
$02BD	$3FFF			ADDLW	255
$02BE	$2AB9			GOTO	L_Lcd_Config_10
$02BF	$	L_Lcd_Config_11:
;lcd.ppas,126 :: 		
$02BF	$0859			MOVF	FARG_Lcd_Config+8, 0
$02C0	$00F0			MOVWF	STACK_0
$02C1	$3001			MOVLW	1
$02C2	$00A3			MOVWF	lcd____menable
$02C3	$0870			MOVF	STACK_0, 0
$02C4	$	L_Lcd_Config_12:
$02C4	$1903			BTFSC	STATUS, Z
$02C5	$2ACA			GOTO	L_Lcd_Config_13
$02C6	$0DA3			RLF	lcd____menable, 1
$02C7	$1023			BCF	lcd____menable, 0
$02C8	$3FFF			ADDLW	255
$02C9	$2AC4			GOTO	L_Lcd_Config_12
$02CA	$	L_Lcd_Config_13:
;lcd.ppas,128 :: 		
$02CA	$0851			MOVF	FARG_Lcd_Config, 0
$02CB	$00A5			MOVWF	lcd_dataport_address
;lcd.ppas,129 :: 		
$02CC	$0856			MOVF	FARG_Lcd_Config+5, 0
$02CD	$00A2			MOVWF	lcd_ctrlport_address
;lcd.ppas,131 :: 		
$02CE	$0851			MOVF	FARG_Lcd_Config, 0
$02CF	$0084			MOVWF	FSR
;lcd.ppas,133 :: 		
$02D0	$0873			MOVF	STACK_3, 0
$02D1	$0474			IORWF	STACK_4, 0
$02D2	$00F0			MOVWF	STACK_0
$02D3	$0872			MOVF	STACK_2, 0
$02D4	$04F0			IORWF	STACK_0, 1
$02D5	$0871			MOVF	STACK_1, 0
$02D6	$04F0			IORWF	STACK_0, 1
$02D7	$09F0			COMF	STACK_0, F
$02D8	$0870			MOVF	STACK_0, 0
$02D9	$0580			ANDWF	INDF, 1
;lcd.ppas,134 :: 		
$02DA	$	lcd_L_56:
$02DA	$1784			BSF	FSR, 7
$02DB	$	lcd_L_57:
;lcd.ppas,135 :: 		
$02DB	$0827			MOVF	lcd____mdb6, 0
$02DC	$0426			IORWF	lcd____mdb7, 0
$02DD	$00F0			MOVWF	STACK_0
$02DE	$0828			MOVF	lcd____mdb5, 0
$02DF	$04F0			IORWF	STACK_0, 1
$02E0	$0829			MOVF	lcd____mdb4, 0
$02E1	$04F0			IORWF	STACK_0, 1
$02E2	$09F0			COMF	STACK_0, F
$02E3	$0870			MOVF	STACK_0, 0
$02E4	$0580			ANDWF	INDF, 1
;lcd.ppas,136 :: 		
$02E5	$1384			BCF	FSR, 7
$02E6	$	lcd_L_59:
;lcd.ppas,139 :: 		
$02E6	$0822			MOVF	lcd_ctrlport_address, 0
$02E7	$0084			MOVWF	FSR
;lcd.ppas,141 :: 		
$02E8	$082B			MOVF	lcd____mrw, 0
$02E9	$0424			IORWF	lcd____mrs, 0
$02EA	$00F0			MOVWF	STACK_0
$02EB	$0823			MOVF	lcd____menable, 0
$02EC	$04F0			IORWF	STACK_0, 1
$02ED	$09F0			COMF	STACK_0, F
$02EE	$0870			MOVF	STACK_0, 0
$02EF	$0580			ANDWF	INDF, 1
;lcd.ppas,142 :: 		
$02F0	$	lcd_L_60:
$02F0	$1784			BSF	FSR, 7
$02F1	$	lcd_L_61:
;lcd.ppas,143 :: 		
$02F1	$082B			MOVF	lcd____mrw, 0
$02F2	$0424			IORWF	lcd____mrs, 0
$02F3	$00F0			MOVWF	STACK_0
$02F4	$0823			MOVF	lcd____menable, 0
$02F5	$04F0			IORWF	STACK_0, 1
$02F6	$09F0			COMF	STACK_0, F
$02F7	$0870			MOVF	STACK_0, 0
$02F8	$0580			ANDWF	INDF, 1
;lcd.ppas,144 :: 		
$02F9	$1384			BCF	FSR, 7
$02FA	$	lcd_L_63:
;lcd.ppas,148 :: 		
$02FA	$0825			MOVF	lcd_dataport_address, 0
$02FB	$0084			MOVWF	FSR
;lcd.ppas,149 :: 		
$02FC	$0828			MOVF	lcd____mdb5, 0
$02FD	$0400			IORWF	INDF, 0
$02FE	$00F0			MOVWF	STACK_0
$02FF	$0829			MOVF	lcd____mdb4, 0
$0300	$0470			IORWF	STACK_0, 0
$0301	$0080			MOVWF	INDF
;lcd.ppas,151 :: 		
$0302	$0822			MOVF	lcd_ctrlport_address, 0
$0303	$0084			MOVWF	FSR
;lcd.ppas,152 :: 		
$0304	$0823			MOVF	lcd____menable, 0
$0305	$0480			IORWF	INDF, 1
;lcd.ppas,153 :: 		
$0306	$0923			COMF	lcd____menable, W
$0307	$00F0			MOVWF	STACK_0
$0308	$0870			MOVF	STACK_0, 0
$0309	$0580			ANDWF	INDF, 1
;lcd.ppas,155 :: 		
$030A	$255C			CALL	_delay_5500us
;lcd.ppas,160 :: 		
$030B	$0823			MOVF	lcd____menable, 0
$030C	$0480			IORWF	INDF, 1
;lcd.ppas,161 :: 		
$030D	$0923			COMF	lcd____menable, W
$030E	$00F0			MOVWF	STACK_0
$030F	$0870			MOVF	STACK_0, 0
$0310	$0580			ANDWF	INDF, 1
;lcd.ppas,163 :: 		
$0311	$255C			CALL	_delay_5500us
;lcd.ppas,168 :: 		
$0312	$0823			MOVF	lcd____menable, 0
$0313	$0480			IORWF	INDF, 1
;lcd.ppas,169 :: 		
$0314	$0923			COMF	lcd____menable, W
$0315	$00F0			MOVWF	STACK_0
$0316	$0870			MOVF	STACK_0, 0
$0317	$0580			ANDWF	INDF, 1
;lcd.ppas,171 :: 		
$0318	$255C			CALL	_delay_5500us
;lcd.ppas,174 :: 		
$0319	$0825			MOVF	lcd_dataport_address, 0
$031A	$0084			MOVWF	FSR
;lcd.ppas,175 :: 		
$031B	$0828			MOVF	lcd____mdb5, 0
$031C	$0480			IORWF	INDF, 1
;lcd.ppas,176 :: 		
$031D	$0929			COMF	lcd____mdb4, W
$031E	$00F0			MOVWF	STACK_0
$031F	$0870			MOVF	STACK_0, 0
$0320	$0580			ANDWF	INDF, 1
;lcd.ppas,178 :: 		
$0321	$0822			MOVF	lcd_ctrlport_address, 0
$0322	$0084			MOVWF	FSR
;lcd.ppas,179 :: 		
$0323	$0823			MOVF	lcd____menable, 0
$0324	$0480			IORWF	INDF, 1
;lcd.ppas,180 :: 		
$0325	$0923			COMF	lcd____menable, W
$0326	$00F0			MOVWF	STACK_0
$0327	$0870			MOVF	STACK_0, 0
$0328	$0580			ANDWF	INDF, 1
;lcd.ppas,182 :: 		
$0329	$255C			CALL	_delay_5500us
;lcd.ppas,187 :: 		
$032A	$0823			MOVF	lcd____menable, 0
$032B	$0480			IORWF	INDF, 1
;lcd.ppas,188 :: 		
$032C	$0923			COMF	lcd____menable, W
$032D	$00F1			MOVWF	STACK_1
$032E	$0871			MOVF	STACK_1, 0
$032F	$0580			ANDWF	INDF, 1
;lcd.ppas,190 :: 		
$0330	$0825			MOVF	lcd_dataport_address, 0
$0331	$0084			MOVWF	FSR
;lcd.ppas,191 :: 		
$0332	$0928			COMF	lcd____mdb5, W
$0333	$00F0			MOVWF	STACK_0
$0334	$0870			MOVF	STACK_0, 0
$0335	$0580			ANDWF	INDF, 1
;lcd.ppas,192 :: 		
$0336	$0826			MOVF	lcd____mdb7, 0
$0337	$0480			IORWF	INDF, 1
;lcd.ppas,194 :: 		
$0338	$0822			MOVF	lcd_ctrlport_address, 0
$0339	$0084			MOVWF	FSR
;lcd.ppas,195 :: 		
$033A	$0823			MOVF	lcd____menable, 0
$033B	$0480			IORWF	INDF, 1
;lcd.ppas,196 :: 		
$033C	$0871			MOVF	STACK_1, 0
$033D	$0580			ANDWF	INDF, 1
;lcd.ppas,198 :: 		
$033E	$255C			CALL	_delay_5500us
;lcd.ppas,201 :: 		
$033F	$0825			MOVF	lcd_dataport_address, 0
$0340	$0084			MOVWF	FSR
;lcd.ppas,202 :: 		
$0341	$0926			COMF	lcd____mdb7, W
$0342	$00F0			MOVWF	STACK_0
$0343	$0870			MOVF	STACK_0, 0
$0344	$0580			ANDWF	INDF, 1
;lcd.ppas,203 :: 		
$0345	$0829			MOVF	lcd____mdb4, 0
$0346	$0480			IORWF	INDF, 1
;lcd.ppas,204 :: 		
$0347	$0822			MOVF	lcd_ctrlport_address, 0
$0348	$0084			MOVWF	FSR
;lcd.ppas,205 :: 		
$0349	$0823			MOVF	lcd____menable, 0
$034A	$0480			IORWF	INDF, 1
;lcd.ppas,206 :: 		
$034B	$0923			COMF	lcd____menable, W
$034C	$00F1			MOVWF	STACK_1
$034D	$0871			MOVF	STACK_1, 0
$034E	$0580			ANDWF	INDF, 1
;lcd.ppas,207 :: 		
$034F	$0825			MOVF	lcd_dataport_address, 0
$0350	$0084			MOVWF	FSR
;lcd.ppas,208 :: 		
$0351	$0929			COMF	lcd____mdb4, W
$0352	$00F0			MOVWF	STACK_0
$0353	$0870			MOVF	STACK_0, 0
$0354	$0580			ANDWF	INDF, 1
;lcd.ppas,209 :: 		
$0355	$0822			MOVF	lcd_ctrlport_address, 0
$0356	$0084			MOVWF	FSR
;lcd.ppas,210 :: 		
$0357	$0823			MOVF	lcd____menable, 0
$0358	$0480			IORWF	INDF, 1
;lcd.ppas,211 :: 		
$0359	$0871			MOVF	STACK_1, 0
$035A	$0580			ANDWF	INDF, 1
;lcd.ppas,213 :: 		
$035B	$255C			CALL	_delay_5500us
;lcd.ppas,218 :: 		
$035C	$0823			MOVF	lcd____menable, 0
$035D	$0480			IORWF	INDF, 1
;lcd.ppas,219 :: 		
$035E	$0923			COMF	lcd____menable, W
$035F	$00F0			MOVWF	STACK_0
$0360	$0870			MOVF	STACK_0, 0
$0361	$0580			ANDWF	INDF, 1
;lcd.ppas,220 :: 		
$0362	$0825			MOVF	lcd_dataport_address, 0
$0363	$0084			MOVWF	FSR
;lcd.ppas,221 :: 		
$0364	$0829			MOVF	lcd____mdb4, 0
$0365	$0480			IORWF	INDF, 1
;lcd.ppas,222 :: 		
$0366	$0822			MOVF	lcd_ctrlport_address, 0
$0367	$0084			MOVWF	FSR
;lcd.ppas,223 :: 		
$0368	$0823			MOVF	lcd____menable, 0
$0369	$0480			IORWF	INDF, 1
;lcd.ppas,224 :: 		
$036A	$0870			MOVF	STACK_0, 0
$036B	$0580			ANDWF	INDF, 1
;lcd.ppas,226 :: 		
$036C	$255C			CALL	_delay_5500us
;lcd.ppas,229 :: 		
$036D	$0825			MOVF	lcd_dataport_address, 0
$036E	$0084			MOVWF	FSR
;lcd.ppas,230 :: 		
$036F	$0929			COMF	lcd____mdb4, W
$0370	$00F0			MOVWF	STACK_0
$0371	$0870			MOVF	STACK_0, 0
$0372	$0580			ANDWF	INDF, 1
;lcd.ppas,231 :: 		
$0373	$0822			MOVF	lcd_ctrlport_address, 0
$0374	$0084			MOVWF	FSR
;lcd.ppas,232 :: 		
$0375	$0823			MOVF	lcd____menable, 0
$0376	$0480			IORWF	INDF, 1
;lcd.ppas,233 :: 		
$0377	$0923			COMF	lcd____menable, W
$0378	$00F1			MOVWF	STACK_1
$0379	$0871			MOVF	STACK_1, 0
$037A	$0580			ANDWF	INDF, 1
;lcd.ppas,234 :: 		
$037B	$0825			MOVF	lcd_dataport_address, 0
$037C	$0084			MOVWF	FSR
;lcd.ppas,235 :: 		
$037D	$0829			MOVF	lcd____mdb4, 0
$037E	$0400			IORWF	INDF, 0
$037F	$00F0			MOVWF	STACK_0
$0380	$0828			MOVF	lcd____mdb5, 0
$0381	$04F0			IORWF	STACK_0, 1
$0382	$0827			MOVF	lcd____mdb6, 0
$0383	$04F0			IORWF	STACK_0, 1
$0384	$0826			MOVF	lcd____mdb7, 0
$0385	$0470			IORWF	STACK_0, 0
$0386	$0080			MOVWF	INDF
;lcd.ppas,236 :: 		
$0387	$0822			MOVF	lcd_ctrlport_address, 0
$0388	$0084			MOVWF	FSR
;lcd.ppas,237 :: 		
$0389	$0823			MOVF	lcd____menable, 0
$038A	$0480			IORWF	INDF, 1
;lcd.ppas,238 :: 		
$038B	$0871			MOVF	STACK_1, 0
$038C	$0580			ANDWF	INDF, 1
;lcd.ppas,240 :: 		
$038D	$255C			CALL	_delay_5500us
;lcd.ppas,242 :: 		
$038E	$3001			MOVLW	1
$038F	$00AA			MOVWF	lcd_lcdcmd_status
$0390	$	lcd_L_55:
;lcd.ppas,243 :: 		
$0390	$0008			RETURN
$0438	$	_lcd_out:
;lcd.ppas,252 :: 		
;lcd.ppas,254 :: 		
$0438	$	lcd_L_68:
$0438	$1303			BCF	STATUS, RP1
$0439	$1283			BCF	STATUS, RP0
$043A	$0851			MOVF	FARG_Lcd_Out, 0
$043B	$3A01			XORLW	1
$043C	$1D03			BTFSS	STATUS, Z
$043D	$2C41			GOTO	lcd_L_69
$043E	$	lcd_L_67:
$043E	$3080			MOVLW	128
$043F	$00D1			MOVWF	FARG_Lcd_Out
$0440	$2C58			GOTO	lcd_L_66
$0441	$	lcd_L_69:
;lcd.ppas,255 :: 		
$0441	$	lcd_L_71:
$0441	$0851			MOVF	FARG_Lcd_Out, 0
$0442	$3A02			XORLW	2
$0443	$1D03			BTFSS	STATUS, Z
$0444	$2C48			GOTO	lcd_L_72
$0445	$	lcd_L_70:
$0445	$30C0			MOVLW	192
$0446	$00D1			MOVWF	FARG_Lcd_Out
$0447	$2C58			GOTO	lcd_L_66
$0448	$	lcd_L_72:
;lcd.ppas,256 :: 		
$0448	$	lcd_L_74:
$0448	$0851			MOVF	FARG_Lcd_Out, 0
$0449	$3A03			XORLW	3
$044A	$1D03			BTFSS	STATUS, Z
$044B	$2C4F			GOTO	lcd_L_75
$044C	$	lcd_L_73:
$044C	$3094			MOVLW	148
$044D	$00D1			MOVWF	FARG_Lcd_Out
$044E	$2C58			GOTO	lcd_L_66
$044F	$	lcd_L_75:
;lcd.ppas,257 :: 		
$044F	$	lcd_L_77:
$044F	$0851			MOVF	FARG_Lcd_Out, 0
$0450	$3A04			XORLW	4
$0451	$1D03			BTFSS	STATUS, Z
$0452	$2C56			GOTO	lcd_L_78
$0453	$	lcd_L_76:
$0453	$30D4			MOVLW	212
$0454	$00D1			MOVWF	FARG_Lcd_Out
;lcd.ppas,258 :: 		
$0455	$2C58			GOTO	lcd_L_66
$0456	$	lcd_L_78:
$0456	$3080			MOVLW	128
$0457	$00D1			MOVWF	FARG_Lcd_Out
$0458	$	lcd_L_66:
;lcd.ppas,260 :: 		
$0458	$0352			DECF	FARG_Lcd_Out+1, 0
$0459	$00F0			MOVWF	STACK_0
$045A	$0851			MOVF	FARG_Lcd_Out, 0
$045B	$07F0			ADDWF	STACK_0, 1
$045C	$0870			MOVF	STACK_0, 0
$045D	$00D1			MOVWF	FARG_Lcd_Out
;lcd.ppas,261 :: 		
$045E	$0870			MOVF	STACK_0, 0
$045F	$00DB			MOVWF	FARG_Lcd_Cmd
$0460	$2391			CALL	_lcd_cmd
;lcd.ppas,262 :: 		
$0461	$01AA			CLRF	lcd_lcdcmd_status, 1
;lcd.ppas,263 :: 		
$0462	$01D4			CLRF	_lcd_out_local_i, 1
;lcd.ppas,264 :: 		
$0463	$	lcd_L_80:
$0463	$0854			MOVF	_lcd_out_local_i, 0
$0464	$0753			ADDWF	FARG_Lcd_Out+2, 0
$0465	$0084			MOVWF	FSR
$0466	$0800			MOVF	INDF, 0
$0467	$00F2			MOVWF	STACK_2
$0468	$0872			MOVF	STACK_2, 0
$0469	$3A00			XORLW	0
$046A	$1903			BTFSC	STATUS, Z
$046B	$2C74			GOTO	lcd_L_81
;lcd.ppas,266 :: 		
$046C	$0854			MOVF	_lcd_out_local_i, 0
$046D	$0753			ADDWF	FARG_Lcd_Out+2, 0
$046E	$0084			MOVWF	FSR
$046F	$0800			MOVF	INDF, 0
$0470	$00DA			MOVWF	FARG_Lcd_Chr_CP
$0471	$257A			CALL	_lcd_chr_cp
;lcd.ppas,267 :: 		
$0472	$0AD4			INCF	_lcd_out_local_i, 1
;lcd.ppas,268 :: 		
$0473	$2C63			GOTO	lcd_L_80
$0474	$	lcd_L_81:
;lcd.ppas,269 :: 		
$0474	$3001			MOVLW	1
$0475	$00AA			MOVWF	lcd_lcdcmd_status
$0476	$	lcd_L_65:
;lcd.ppas,270 :: 		
$0476	$0008			RETURN
$04A9	$	_adc_read:
;ADClib_88X.ppas,9 :: 		
;ADClib_88X.ppas,10 :: 		
$04A9	$30C0			MOVLW	192
$04AA	$1303			BCF	STATUS, RP1
$04AB	$1283			BCF	STATUS, RP0
$04AC	$009F			MOVWF	ADCON0
;ADClib_88X.ppas,11 :: 		
$04AD	$0851			MOVF	FARG_Adc_Read, 0
$04AE	$00F0			MOVWF	STACK_0
$04AF	$0DF0			RLF	STACK_0, 1
$04B0	$1070			BCF	STACK_0, 0
$04B1	$0DF0			RLF	STACK_0, 1
$04B2	$1070			BCF	STACK_0, 0
$04B3	$0870			MOVF	STACK_0, 0
$04B4	$049F			IORWF	ADCON0, 1
;ADClib_88X.ppas,12 :: 		
$04B5	$	ADClib_88X_L_1:
$04B5	$1683			BSF	STATUS, RP0
$04B6	$179F			BSF	ADCON1, 7
$04B7	$	ADClib_88X_L_2:
;ADClib_88X.ppas,15 :: 		
$04B7	$	ADClib_88X_L_3:
$04B7	$1283			BCF	STATUS, RP0
$04B8	$141F			BSF	ADCON0, 0
$04B9	$	ADClib_88X_L_4:
;ADClib_88X.ppas,18 :: 		
$04B9	$258B			CALL	_delay_22us
;ADClib_88X.ppas,21 :: 		
$04BA	$	ADClib_88X_L_5:
$04BA	$149F			BSF	ADCON0, 1
$04BB	$	ADClib_88X_L_6:
;ADClib_88X.ppas,24 :: 		
$04BB	$	ADClib_88X_L_8:
$04BB	$081F			MOVF	ADCON0, 0
$04BC	$00F2			MOVWF	STACK_2
$04BD	$3000			MOVLW	0
$04BE	$18F2			BTFSC	STACK_2, 1
$04BF	$3001			MOVLW	1
$04C0	$00F2			MOVWF	STACK_2
$04C1	$0872			MOVF	STACK_2, 0
$04C2	$3A00			XORLW	0
$04C3	$1D03			BTFSS	STATUS, Z
$04C4	$2CBB			GOTO	ADClib_88X_L_8
;ADClib_88X.ppas,26 :: 		
$04C5	$	ADClib_88X_L_9:
;ADClib_88X.ppas,29 :: 		
$04C5	$101F			BCF	ADCON0, 0
$04C6	$	ADClib_88X_L_13:
;ADClib_88X.ppas,32 :: 		
$04C6	$081E			MOVF	ADRESH, 0
$04C7	$00F2			MOVWF	STACK_2
$04C8	$01F3			CLRF	STACK_2+1
$04C9	$0872			MOVF	STACK_2, 0
$04CA	$00F3			MOVWF	STACK_2+1
$04CB	$01F2			CLRF	STACK_2
$04CC	$1683			BSF	STATUS, RP0
$04CD	$081E			MOVF	ADRESL, 0
$04CE	$0472			IORWF	STACK_2, 0
$04CF	$1283			BCF	STATUS, RP0
$04D0	$00D2			MOVWF	_adc_read_local_result
$04D1	$0873			MOVF	STACK_2+1, 0
$04D2	$00D3			MOVWF	_adc_read_local_result+1
$04D3	$3000			MOVLW	0
$04D4	$04D3			IORWF	_adc_read_local_result+1, 1
$04D5	$	ADClib_88X_L_0:
;ADClib_88X.ppas,33 :: 		
$04D5	$0852			MOVF	_adc_read_local_result, 0
$04D6	$00F0			MOVWF	STACK_0
$04D7	$0853			MOVF	_adc_read_local_result+1, 0
$04D8	$00F1			MOVWF	STACK_0+1
$04D9	$0008			RETURN
$0477	$	_lcd_chr:
;lcd.ppas,78 :: 		
;lcd.ppas,80 :: 		
$0477	$	lcd_L_37:
$0477	$1303			BCF	STATUS, RP1
$0478	$1283			BCF	STATUS, RP0
$0479	$0851			MOVF	FARG_Lcd_Chr, 0
$047A	$3A01			XORLW	1
$047B	$1D03			BTFSS	STATUS, Z
$047C	$2C80			GOTO	lcd_L_38
$047D	$	lcd_L_36:
$047D	$3080			MOVLW	128
$047E	$00D1			MOVWF	FARG_Lcd_Chr
$047F	$2C97			GOTO	lcd_L_35
$0480	$	lcd_L_38:
;lcd.ppas,81 :: 		
$0480	$	lcd_L_40:
$0480	$0851			MOVF	FARG_Lcd_Chr, 0
$0481	$3A02			XORLW	2
$0482	$1D03			BTFSS	STATUS, Z
$0483	$2C87			GOTO	lcd_L_41
$0484	$	lcd_L_39:
$0484	$30C0			MOVLW	192
$0485	$00D1			MOVWF	FARG_Lcd_Chr
$0486	$2C97			GOTO	lcd_L_35
$0487	$	lcd_L_41:
;lcd.ppas,82 :: 		
$0487	$	lcd_L_43:
$0487	$0851			MOVF	FARG_Lcd_Chr, 0
$0488	$3A03			XORLW	3
$0489	$1D03			BTFSS	STATUS, Z
$048A	$2C8E			GOTO	lcd_L_44
$048B	$	lcd_L_42:
$048B	$3094			MOVLW	148
$048C	$00D1			MOVWF	FARG_Lcd_Chr
$048D	$2C97			GOTO	lcd_L_35
$048E	$	lcd_L_44:
;lcd.ppas,83 :: 		
$048E	$	lcd_L_46:
$048E	$0851			MOVF	FARG_Lcd_Chr, 0
$048F	$3A04			XORLW	4
$0490	$1D03			BTFSS	STATUS, Z
$0491	$2C95			GOTO	lcd_L_47
$0492	$	lcd_L_45:
$0492	$30D4			MOVLW	212
$0493	$00D1			MOVWF	FARG_Lcd_Chr
;lcd.ppas,84 :: 		
$0494	$2C97			GOTO	lcd_L_35
$0495	$	lcd_L_47:
$0495	$3080			MOVLW	128
$0496	$00D1			MOVWF	FARG_Lcd_Chr
$0497	$	lcd_L_35:
;lcd.ppas,86 :: 		
$0497	$0852			MOVF	FARG_Lcd_Chr+1, 0
$0498	$0751			ADDWF	FARG_Lcd_Chr, 0
$0499	$00F0			MOVWF	STACK_0
$049A	$03F0			DECF	STACK_0, 1
$049B	$0870			MOVF	STACK_0, 0
$049C	$00D1			MOVWF	FARG_Lcd_Chr
;lcd.ppas,88 :: 		
$049D	$3001			MOVLW	1
$049E	$00AA			MOVWF	lcd_lcdcmd_status
;lcd.ppas,89 :: 		
$049F	$0870			MOVF	STACK_0, 0
$04A0	$00DB			MOVWF	FARG_Lcd_Cmd
$04A1	$2391			CALL	_lcd_cmd
;lcd.ppas,91 :: 		
$04A2	$01AA			CLRF	lcd_lcdcmd_status, 1
;lcd.ppas,92 :: 		
$04A3	$0853			MOVF	FARG_Lcd_Chr+2, 0
$04A4	$00DB			MOVWF	FARG_Lcd_Cmd
$04A5	$2391			CALL	_lcd_cmd
;lcd.ppas,93 :: 		
$04A6	$3001			MOVLW	1
$04A7	$00AA			MOVWF	lcd_lcdcmd_status
$04A8	$	lcd_L_34:
;lcd.ppas,94 :: 		
$04A8	$0008			RETURN
$054A	$	_usart_write:
;USART_c67.ppas,40 :: 		
;USART_c67.ppas,42 :: 		
$054A	$	USART_c67_L_14:
$054A	$1303			BCF	STATUS, RP1
$054B	$1683			BSF	STATUS, RP0
$054C	$0818			MOVF	TXSTA, 0
$054D	$00F1			MOVWF	STACK_1
$054E	$3000			MOVLW	0
$054F	$18F1			BTFSC	STACK_1, 1
$0550	$3001			MOVLW	1
$0551	$00F1			MOVWF	STACK_1
$0552	$0871			MOVF	STACK_1, 0
$0553	$3A00			XORLW	0
$0554	$1D03			BTFSS	STATUS, Z
$0555	$2D58			GOTO	USART_c67_L_15
;USART_c67.ppas,43 :: 		
$0556	$0000			NOP
$0557	$2D4A			GOTO	USART_c67_L_14
$0558	$	USART_c67_L_15:
;USART_c67.ppas,44 :: 		
$0558	$1283			BCF	STATUS, RP0
$0559	$0851			MOVF	FARG_USART_Write, 0
$055A	$0099			MOVWF	TXREG
$055B	$	USART_c67_L_12:
;USART_c67.ppas,45 :: 		
$055B	$0008			RETURN
$0522	$	_usart_init:
;USART_c67.ppas,22 :: 		
;USART_c67.ppas,24 :: 		
$0522	$	USART_c67_L_1:
$0522	$1303			BCF	STATUS, RP1
$0523	$1683			BSF	STATUS, RP0
$0524	$1698			BSF	TXSTA, 5
$0525	$	USART_c67_L_2:
;USART_c67.ppas,25 :: 		
$0525	$3090			MOVLW	144
$0526	$1283			BCF	STATUS, RP0
$0527	$0098			MOVWF	RCSTA
;USART_c67.ppas,31 :: 		
$0528	$	USART_c67_L_3:
$0528	$1683			BSF	STATUS, RP0
$0529	$1787			BSF	TRISC, 7
$052A	$	USART_c67_L_4:
;USART_c67.ppas,32 :: 		
$052A	$1307			BCF	TRISC, 6
$052B	$	USART_c67_L_6:
;USART_c67.ppas,35 :: 		
$052B	$	USART_c67_L_8:
$052B	$1283			BCF	STATUS, RP0
$052C	$080C			MOVF	PIR1, 0
$052D	$00F1			MOVWF	STACK_1
$052E	$3000			MOVLW	0
$052F	$1AF1			BTFSC	STACK_1, 5
$0530	$3001			MOVLW	1
$0531	$00F1			MOVWF	STACK_1
$0532	$0871			MOVF	STACK_1, 0
$0533	$3A01			XORLW	1
$0534	$1903			BTFSC	STATUS, Z
$0535	$2D2B			GOTO	USART_c67_L_8
;USART_c67.ppas,36 :: 		
$0536	$	USART_c67_L_9:
$0536	$	USART_c67_L_0:
;USART_c67.ppas,37 :: 		
$0536	$0008			RETURN
$04DA	$	_mul_16x16_u:
$04DA	$1303			BCF	STATUS, RP1
$04DB	$1283			BCF	STATUS, RP0
;math.ppas,42 :: 		
;math.ppas,44 :: 		
$04DC	$01FB			CLRF	STACK_11
;math.ppas,45 :: 		
$04DD	$01FA			CLRF	STACK_10
;math.ppas,46 :: 		
$04DE	$01F9			CLRF	STACK_9
;math.ppas,47 :: 		
$04DF	$3080			MOVLW	128
;math.ppas,48 :: 		
$04E0	$00F8			MOVWF	STACK_8
;math.ppas,49 :: 		
$04E1	$0CF1			RRF	STACK_1, F
;math.ppas,50 :: 		
$04E2	$0CF0			RRF	STACK_0, F
;math.ppas,51 :: 		
$04E3	$1C03			BTFSS	STATUS, C
;math.ppas,52 :: 		
$04E4	$2CEE			GOTO	$+10
;math.ppas,53 :: 		
$04E5	$0874			MOVF	STACK_4, W
;math.ppas,54 :: 		
$04E6	$07F9			ADDWF	STACK_9, F
;math.ppas,55 :: 		
$04E7	$0875			MOVF	STACK_5, W
;math.ppas,56 :: 		
$04E8	$1803			BTFSC	STATUS, C
;math.ppas,57 :: 		
$04E9	$0F75			INCFSZ	STACK_5, W
;math.ppas,58 :: 		
$04EA	$07FA			ADDWF	STACK_10, F
;math.ppas,59 :: 		
$04EB	$1803			BTFSC	STATUS, C
;math.ppas,60 :: 		
$04EC	$0AFB			INCF	STACK_11, F
;math.ppas,61 :: 		
$04ED	$1003			BCF	STATUS, C
;math.ppas,62 :: 		
$04EE	$1FF0			BTFSS	STACK_0, 7
;math.ppas,63 :: 		
$04EF	$2CF6			GOTO	$+7
;math.ppas,64 :: 		
$04F0	$0874			MOVF	STACK_4, W
;math.ppas,65 :: 		
$04F1	$07FA			ADDWF	STACK_10, F
;math.ppas,66 :: 		
$04F2	$0875			MOVF	STACK_5, W
;math.ppas,67 :: 		
$04F3	$1803			BTFSC	STATUS, C
;math.ppas,68 :: 		
$04F4	$0F75			INCFSZ	STACK_5, W
;math.ppas,69 :: 		
$04F5	$07FB			ADDWF	STACK_11, F
;math.ppas,70 :: 		
$04F6	$0CFB			RRF	STACK_11, F
;math.ppas,71 :: 		
$04F7	$0CFA			RRF	STACK_10, F
;math.ppas,72 :: 		
$04F8	$0CF9			RRF	STACK_9, F
;math.ppas,73 :: 		
$04F9	$0CF8			RRF	STACK_8, F
;math.ppas,74 :: 		
$04FA	$1C03			BTFSS	STATUS, C
;math.ppas,75 :: 		
$04FB	$2CE1			GOTO	$-26
;math.ppas,76 :: 		
$04FC	$087B			MOVF	STACK_11, W
;math.ppas,77 :: 		
$04FD	$00F3			MOVWF	STACK_3
;math.ppas,78 :: 		
$04FE	$087A			MOVF	STACK_10, W
;math.ppas,79 :: 		
$04FF	$00F2			MOVWF	STACK_2
;math.ppas,80 :: 		
$0500	$0879			MOVF	STACK_9, W
;math.ppas,81 :: 		
$0501	$00F1			MOVWF	STACK_1
;math.ppas,82 :: 		
$0502	$0878			MOVF	STACK_8, W
;math.ppas,83 :: 		
$0503	$00F0			MOVWF	STACK_0
;math.ppas,84 :: 		
$0504	$	math_L_1:
;math.ppas,85 :: 		
$0504	$0008			RETURN
$0505	$	_div_16x16_u:
$0505	$1303			BCF	STATUS, RP1
$0506	$1283			BCF	STATUS, RP0
;math.ppas,108 :: 		
;math.ppas,110 :: 		
$0507	$01F8			CLRF	STACK_8
;math.ppas,111 :: 		
$0508	$01F9			CLRF	STACK_9
;math.ppas,112 :: 		
$0509	$3010			MOVLW	16
;math.ppas,113 :: 		
$050A	$00FC			MOVWF	STACK_12
;math.ppas,114 :: 		
$050B	$0D71			RLF	STACK_1, W
;math.ppas,115 :: 		
$050C	$0DF8			RLF	STACK_8, F
;math.ppas,116 :: 		
$050D	$0DF9			RLF	STACK_9, F
;math.ppas,117 :: 		
$050E	$0874			MOVF	STACK_4, W
;math.ppas,118 :: 		
$050F	$02F8			SUBWF	STACK_8, F
;math.ppas,119 :: 		
$0510	$0875			MOVF	STACK_5, W
;math.ppas,120 :: 		
$0511	$1C03			BTFSS	STATUS, C
;math.ppas,121 :: 		
$0512	$0F75			INCFSZ	STACK_5, W
;math.ppas,122 :: 		
$0513	$02F9			SUBWF	STACK_9, F
;math.ppas,123 :: 		
$0514	$1803			BTFSC	STATUS, C
;math.ppas,124 :: 		
$0515	$2D1D			GOTO	$+8
;math.ppas,125 :: 		
$0516	$0874			MOVF	STACK_4, W
;math.ppas,126 :: 		
$0517	$07F8			ADDWF	STACK_8, F
;math.ppas,127 :: 		
$0518	$0875			MOVF	STACK_5, W
;math.ppas,128 :: 		
$0519	$1803			BTFSC	STATUS, C
;math.ppas,129 :: 		
$051A	$0F75			INCFSZ	STACK_5, W
;math.ppas,130 :: 		
$051B	$07F9			ADDWF	STACK_9, F
;math.ppas,131 :: 		
$051C	$1003			BCF	STATUS, C
;math.ppas,132 :: 		
$051D	$0DF0			RLF	STACK_0, F
;math.ppas,133 :: 		
$051E	$0DF1			RLF	STACK_1, F
;math.ppas,134 :: 		
$051F	$0BFC			DECFSZ	STACK_12, F
;math.ppas,135 :: 		
$0520	$2D0B			GOTO	$-21
;math.ppas,136 :: 		
$0521	$	math_L_3:
;math.ppas,137 :: 		
$0521	$0008			RETURN
$0090	$	_main:
;CodigoIncubadora.pbas,56 :: 		main:
$0090	$	_main_main:
;CodigoIncubadora.pbas,58 :: 		OPTION_REG=%11000101 ' Configuracion de Puertos analogicos / digitales AN0 - AN13
$0090	$30C5			MOVLW	197
$0091	$1303			BCF	STATUS, RP1
$0092	$1683			BSF	STATUS, RP0
$0093	$0081			MOVWF	OPTION_REG
;CodigoIncubadora.pbas,59 :: 		INTCON = 0
$0094	$018B			CLRF	INTCON, 1
;CodigoIncubadora.pbas,60 :: 		ANSEL =  %00000000           'REGISTRO CONFIG. O DIGITAL, 1 ANALOGICO
$0095	$1703			BSF	STATUS, RP1
$0096	$0188			CLRF	ANSEL, 1
;CodigoIncubadora.pbas,61 :: 		ANSELH = %00000010           'REGISTRO CONFIG. O DIGITAL, 1 ANALOGICO
$0097	$3002			MOVLW	2
$0098	$0089			MOVWF	ANSELH
;CodigoIncubadora.pbas,64 :: 		trisa  = %00000000           ' Configuracion IN/OUT PORTA
$0099	$1303			BCF	STATUS, RP1
$009A	$0185			CLRF	TRISA, 1
;CodigoIncubadora.pbas,65 :: 		trisb  = %00001001           ' Configuracion IN/OUT PORTB
$009B	$3009			MOVLW	9
$009C	$0086			MOVWF	TRISB
;CodigoIncubadora.pbas,66 :: 		trisc  = %10000000           ' Configuracion IN/OUT PORTC
$009D	$3080			MOVLW	128
$009E	$0087			MOVWF	TRISC
;CodigoIncubadora.pbas,70 :: 		PORTA  = %00000000           ' Inicializacion PORTA
$009F	$1283			BCF	STATUS, RP0
$00A0	$0185			CLRF	PORTA, 1
;CodigoIncubadora.pbas,71 :: 		PORTB  = %00000000           ' Inicializacion PORTC
$00A1	$0186			CLRF	PORTB, 1
;CodigoIncubadora.pbas,72 :: 		PORTC  = %00000000           ' Inicializacion PORTC
$00A2	$0187			CLRF	PORTC, 1
;CodigoIncubadora.pbas,74 :: 		flag=0
$00A3	$01AC			CLRF	_flag, 1
;CodigoIncubadora.pbas,75 :: 		intensidad=0
$00A4	$01A1			CLRF	_intensidad, 1
;CodigoIncubadora.pbas,76 :: 		muestras=0
$00A5	$01AD			CLRF	_muestras, 1
;CodigoIncubadora.pbas,77 :: 		temp_ac=0
$00A6	$01AE			CLRF	_temp_ac
$00A7	$01AF			CLRF	_temp_ac+1
;CodigoIncubadora.pbas,78 :: 		temp_prom=0
$00A8	$01B0			CLRF	_temp_prom
$00A9	$01B1			CLRF	_temp_prom+1
;CodigoIncubadora.pbas,79 :: 		set_temp=0
$00AA	$01A0			CLRF	_set_temp, 1
;CodigoIncubadora.pbas,80 :: 		USART_Init(9600)
$00AB	$3019			MOVLW	25
$00AC	$1683			BSF	STATUS, RP0
$00AD	$0099			MOVWF	SPBRG
$00AE	$1518			BSF	TXSTA, BRGH
$00AF	$2522			CALL	_usart_init
;CodigoIncubadora.pbas,81 :: 		Delay_ms(100)
$00B0	$3082			MOVLW	130
$00B1	$00FB			MOVWF	STACK_11
$00B2	$30FF			MOVLW	255
$00B3	$00FA			MOVWF	STACK_10
$00B4	$0BFB			DECFSZ	STACK_11, F
$00B5	$28B7			GOTO	$+2
$00B6	$28BA			GOTO	$+4
$00B7	$0BFA			DECFSZ	STACK_10, F
$00B8	$28B7			GOTO	$-1
$00B9	$28B4			GOTO	$-5
$00BA	$3087			MOVLW	135
$00BB	$00FA			MOVWF	STACK_10
$00BC	$0BFA			DECFSZ	STACK_10, F
$00BD	$28BC			GOTO	$-1
$00BE	$0000			NOP
;CodigoIncubadora.pbas,83 :: 		Lcd_Config(PORTA,6,5,4,3,PORTA,0,1,2) 'Lcd_Config(ddata_portd,db3, db2, db1,
$00BF	$3005			MOVLW	PORTA
$00C0	$00D1			MOVWF	FARG_Lcd_Config
$00C1	$3006			MOVLW	6
$00C2	$00D2			MOVWF	FARG_Lcd_Config+1
$00C3	$3005			MOVLW	5
$00C4	$00D3			MOVWF	FARG_Lcd_Config+2
$00C5	$3004			MOVLW	4
$00C6	$00D4			MOVWF	FARG_Lcd_Config+3
$00C7	$3003			MOVLW	3
$00C8	$00D5			MOVWF	FARG_Lcd_Config+4
$00C9	$3005			MOVLW	PORTA
$00CA	$00D6			MOVWF	FARG_Lcd_Config+5
$00CB	$01D7			CLRF	FARG_Lcd_Config+6, 1
$00CC	$3001			MOVLW	1
$00CD	$00D8			MOVWF	FARG_Lcd_Config+7
$00CE	$3002			MOVLW	2
$00CF	$00D9			MOVWF	FARG_Lcd_Config+8
$00D0	$2272			CALL	_lcd_config
;CodigoIncubadora.pbas,85 :: 		Delay_ms(100)
$00D1	$3082			MOVLW	130
$00D2	$00FB			MOVWF	STACK_11
$00D3	$30FF			MOVLW	255
$00D4	$00FA			MOVWF	STACK_10
$00D5	$0BFB			DECFSZ	STACK_11, F
$00D6	$28D8			GOTO	$+2
$00D7	$28DB			GOTO	$+4
$00D8	$0BFA			DECFSZ	STACK_10, F
$00D9	$28D8			GOTO	$-1
$00DA	$28D5			GOTO	$-5
$00DB	$3087			MOVLW	135
$00DC	$00FA			MOVWF	STACK_10
$00DD	$0BFA			DECFSZ	STACK_10, F
$00DE	$28DD			GOTO	$-1
$00DF	$0000			NOP
;CodigoIncubadora.pbas,86 :: 		Lcd_Cmd(Lcd_CURSOR_OFF)               'Lcd_Cmd(commando)
$00E0	$300C			MOVLW	12
$00E1	$00DB			MOVWF	FARG_Lcd_Cmd
$00E2	$2391			CALL	_lcd_cmd
;CodigoIncubadora.pbas,87 :: 		LCD_Cmd(LCD_CLEAR)
$00E3	$3001			MOVLW	1
$00E4	$00DB			MOVWF	FARG_Lcd_Cmd
$00E5	$2391			CALL	_lcd_cmd
;CodigoIncubadora.pbas,88 :: 		Lcd_Out(1, 1,"Medidor Temperatura")
$00E6	$3001			MOVLW	1
$00E7	$00D1			MOVWF	FARG_Lcd_Out
$00E8	$3001			MOVLW	1
$00E9	$00D2			MOVWF	FARG_Lcd_Out+1
$00EA	$304D			MOVLW	77
$00EB	$00BD			MOVWF	?main_Local_Text+0
$00EC	$3065			MOVLW	101
$00ED	$00BE			MOVWF	?main_Local_Text+1
$00EE	$3064			MOVLW	100
$00EF	$00BF			MOVWF	?main_Local_Text+2
$00F0	$3069			MOVLW	105
$00F1	$00C0			MOVWF	?main_Local_Text+3
$00F2	$3064			MOVLW	100
$00F3	$00C1			MOVWF	?main_Local_Text+4
$00F4	$306F			MOVLW	111
$00F5	$00C2			MOVWF	?main_Local_Text+5
$00F6	$3072			MOVLW	114
$00F7	$00C3			MOVWF	?main_Local_Text+6
$00F8	$3020			MOVLW	32
$00F9	$00C4			MOVWF	?main_Local_Text+7
$00FA	$3054			MOVLW	84
$00FB	$00C5			MOVWF	?main_Local_Text+8
$00FC	$3065			MOVLW	101
$00FD	$00C6			MOVWF	?main_Local_Text+9
$00FE	$306D			MOVLW	109
$00FF	$00C7			MOVWF	?main_Local_Text+10
$0100	$3070			MOVLW	112
$0101	$00C8			MOVWF	?main_Local_Text+11
$0102	$3065			MOVLW	101
$0103	$00C9			MOVWF	?main_Local_Text+12
$0104	$3072			MOVLW	114
$0105	$00CA			MOVWF	?main_Local_Text+13
$0106	$3061			MOVLW	97
$0107	$00CB			MOVWF	?main_Local_Text+14
$0108	$3074			MOVLW	116
$0109	$00CC			MOVWF	?main_Local_Text+15
$010A	$3075			MOVLW	117
$010B	$00CD			MOVWF	?main_Local_Text+16
$010C	$3072			MOVLW	114
$010D	$00CE			MOVWF	?main_Local_Text+17
$010E	$3061			MOVLW	97
$010F	$00CF			MOVWF	?main_Local_Text+18
$0110	$01D0			CLRF	?main_Local_Text+19
$0111	$303D			MOVLW	?main_Local_Text
$0112	$00D3			MOVWF	FARG_Lcd_Out+2
$0113	$2438			CALL	_lcd_out
;CodigoIncubadora.pbas,89 :: 		INTCON =%11010000
$0114	$30D0			MOVLW	208
$0115	$008B			MOVWF	INTCON
;CodigoIncubadora.pbas,90 :: 		PIE1 = %00100000
$0116	$3020			MOVLW	32
$0117	$1683			BSF	STATUS, RP0
$0118	$008C			MOVWF	PIE1
;CodigoIncubadora.pbas,91 :: 		PIR1=0
$0119	$1283			BCF	STATUS, RP0
$011A	$018C			CLRF	PIR1, 1
;CodigoIncubadora.pbas,92 :: 		Delay_ms(100)
$011B	$3082			MOVLW	130
$011C	$00FB			MOVWF	STACK_11
$011D	$30FF			MOVLW	255
$011E	$00FA			MOVWF	STACK_10
$011F	$0BFB			DECFSZ	STACK_11, F
$0120	$2922			GOTO	$+2
$0121	$2925			GOTO	$+4
$0122	$0BFA			DECFSZ	STACK_10, F
$0123	$2922			GOTO	$-1
$0124	$291F			GOTO	$-5
$0125	$3087			MOVLW	135
$0126	$00FA			MOVWF	STACK_10
$0127	$0BFA			DECFSZ	STACK_10, F
$0128	$2927			GOTO	$-1
$0129	$0000			NOP
;CodigoIncubadora.pbas,94 :: 		while  TRUE      ' Lazo infinito Bucle While
$012A	$	CodigoIncubadora_L_65:
;CodigoIncubadora.pbas,96 :: 		do
$012A	$	CodigoIncubadora_L_69:
;CodigoIncubadora.pbas,97 :: 		analogico = Adc_Read(9)
$012A	$3009			MOVLW	9
$012B	$00D1			MOVWF	FARG_Adc_Read
$012C	$24A9			CALL	_adc_read
$012D	$0870			MOVF	STACK_0, 0
$012E	$00B2			MOVWF	_analogico
$012F	$0871			MOVF	STACK_0+1, 0
$0130	$00B3			MOVWF	_analogico+1
;CodigoIncubadora.pbas,98 :: 		temperatura=(analogico*100/230) ''
$0131	$3064			MOVLW	100
$0132	$00F4			MOVWF	STACK_4
$0133	$01F5			CLRF	STACK_4+1
$0134	$24DA			CALL	_mul_16x16_u
$0135	$30E6			MOVLW	230
$0136	$00F4			MOVWF	STACK_4
$0137	$01F5			CLRF	STACK_4+1
$0138	$2505			CALL	_div_16x16_u
$0139	$0870			MOVF	STACK_0, 0
$013A	$00B4			MOVWF	_temperatura
$013B	$0871			MOVF	STACK_0+1, 0
$013C	$00B5			MOVWF	_temperatura+1
;CodigoIncubadora.pbas,99 :: 		inc(muestras)
$013D	$0AAD			INCF	_muestras, 1
;CodigoIncubadora.pbas,100 :: 		Delay_ms(2)
$013E	$3003			MOVLW	3
$013F	$00FB			MOVWF	STACK_11
$0140	$30FF			MOVLW	255
$0141	$00FA			MOVWF	STACK_10
$0142	$0BFB			DECFSZ	STACK_11, F
$0143	$2945			GOTO	$+2
$0144	$2948			GOTO	$+4
$0145	$0BFA			DECFSZ	STACK_10, F
$0146	$2945			GOTO	$-1
$0147	$2942			GOTO	$-5
$0148	$3096			MOVLW	150
$0149	$00FA			MOVWF	STACK_10
$014A	$0BFA			DECFSZ	STACK_10, F
$014B	$294A			GOTO	$-1
;CodigoIncubadora.pbas,101 :: 		temp_ac= temp_ac + temperatura
$014C	$0870			MOVF	STACK_0, 0
$014D	$07AE			ADDWF	_temp_ac, 1
$014E	$0871			MOVF	STACK_0+1, 0
$014F	$1803			BTFSC	STATUS, C
$0150	$3F01			ADDLW	1
$0151	$07AF			ADDWF	_temp_ac+1, 1
;CodigoIncubadora.pbas,102 :: 		loop until (muestras >=200)
$0152	$	CodigoIncubadora_L_70:
$0152	$30C8			MOVLW	200
$0153	$022D			SUBWF	_muestras, 0
$0154	$1C03			BTFSS	STATUS, C
$0155	$2957			GOTO	CodigoIncubadora_L_72
$0156	$	CodigoIncubadora_L_73:
$0156	$2958			GOTO	CodigoIncubadora_L_71
$0157	$	CodigoIncubadora_L_72:
$0157	$292A			GOTO	CodigoIncubadora_L_69
$0158	$	CodigoIncubadora_L_71:
;CodigoIncubadora.pbas,103 :: 		temp_prom = (temp_ac /200)
$0158	$30C8			MOVLW	200
$0159	$00F4			MOVWF	STACK_4
$015A	$01F5			CLRF	STACK_4+1
$015B	$082E			MOVF	_temp_ac, 0
$015C	$00F0			MOVWF	STACK_0
$015D	$082F			MOVF	_temp_ac+1, 0
$015E	$00F1			MOVWF	STACK_0+1
$015F	$2505			CALL	_div_16x16_u
$0160	$0870			MOVF	STACK_0, 0
$0161	$00B0			MOVWF	_temp_prom
$0162	$0871			MOVF	STACK_0+1, 0
$0163	$00B1			MOVWF	_temp_prom+1
;CodigoIncubadora.pbas,105 :: 		if(temp_prom > set_temp )then
$0164	$0871			MOVF	STACK_0+1, 0
$0165	$3C00			SUBLW	0
$0166	$1D03			BTFSS	STATUS, Z
$0167	$296A			GOTO	L_main_0
$0168	$0870			MOVF	STACK_0, 0
$0169	$0220			SUBWF	_set_temp, 0
$016A	$	L_main_0:
$016A	$1803			BTFSC	STATUS, C
$016B	$2972			GOTO	CodigoIncubadora_L_75
$016C	$	CodigoIncubadora_L_74:
;CodigoIncubadora.pbas,106 :: 		if(intensidad <8)then
$016C	$3008			MOVLW	8
$016D	$0221			SUBWF	_intensidad, 0
$016E	$1803			BTFSC	STATUS, C
$016F	$2971			GOTO	CodigoIncubadora_L_78
$0170	$	CodigoIncubadora_L_77:
;CodigoIncubadora.pbas,107 :: 		inc(intensidad)
$0170	$0AA1			INCF	_intensidad, 1
$0171	$	CodigoIncubadora_L_78:
;CodigoIncubadora.pbas,108 :: 		end if
$0171	$	CodigoIncubadora_L_79:
$0171	$2977			GOTO	CodigoIncubadora_L_76
;CodigoIncubadora.pbas,109 :: 		else
$0172	$	CodigoIncubadora_L_75:
;CodigoIncubadora.pbas,110 :: 		if(intensidad > 0)then
$0172	$0821			MOVF	_intensidad, 0
$0173	$3C00			SUBLW	0
$0174	$1803			BTFSC	STATUS, C
$0175	$2977			GOTO	CodigoIncubadora_L_81
$0176	$	CodigoIncubadora_L_80:
;CodigoIncubadora.pbas,111 :: 		dec(intensidad)
$0176	$03A1			DECF	_intensidad, 1
$0177	$	CodigoIncubadora_L_81:
;CodigoIncubadora.pbas,112 :: 		end if
$0177	$	CodigoIncubadora_L_82:
;CodigoIncubadora.pbas,113 :: 		end if
$0177	$	CodigoIncubadora_L_76:
;CodigoIncubadora.pbas,115 :: 		centena=(( temp_prom/100) mod 10)+ 48
$0177	$3064			MOVLW	100
$0178	$00F4			MOVWF	STACK_4
$0179	$01F5			CLRF	STACK_4+1
$017A	$0830			MOVF	_temp_prom, 0
$017B	$00F0			MOVWF	STACK_0
$017C	$0831			MOVF	_temp_prom+1, 0
$017D	$00F1			MOVWF	STACK_0+1
$017E	$2505			CALL	_div_16x16_u
$017F	$300A			MOVLW	10
$0180	$00F4			MOVWF	STACK_4
$0181	$01F5			CLRF	STACK_4+1
$0182	$2505			CALL	_div_16x16_u
$0183	$0878			MOVF	STACK_8, 0
$0184	$00F0			MOVWF	STACK_0
$0185	$0879			MOVF	STACK_9, 0
$0186	$00F1			MOVWF	STACK_1
$0187	$3030			MOVLW	48
$0188	$07F0			ADDWF	STACK_0, 1
$0189	$1803			BTFSC	STATUS, C
$018A	$0AF1			INCF	STACK_0+1, 1
$018B	$0870			MOVF	STACK_0, 0
$018C	$00B6			MOVWF	_centena
;CodigoIncubadora.pbas,116 :: 		decena=(( temp_prom/10) mod 10) + 48
$018D	$300A			MOVLW	10
$018E	$00F4			MOVWF	STACK_4
$018F	$01F5			CLRF	STACK_4+1
$0190	$0830			MOVF	_temp_prom, 0
$0191	$00F0			MOVWF	STACK_0
$0192	$0831			MOVF	_temp_prom+1, 0
$0193	$00F1			MOVWF	STACK_0+1
$0194	$2505			CALL	_div_16x16_u
$0195	$300A			MOVLW	10
$0196	$00F4			MOVWF	STACK_4
$0197	$01F5			CLRF	STACK_4+1
$0198	$2505			CALL	_div_16x16_u
$0199	$0878			MOVF	STACK_8, 0
$019A	$00F0			MOVWF	STACK_0
$019B	$0879			MOVF	STACK_9, 0
$019C	$00F1			MOVWF	STACK_1
$019D	$3030			MOVLW	48
$019E	$07F0			ADDWF	STACK_0, 1
$019F	$1803			BTFSC	STATUS, C
$01A0	$0AF1			INCF	STACK_0+1, 1
$01A1	$0870			MOVF	STACK_0, 0
$01A2	$00B7			MOVWF	_decena
;CodigoIncubadora.pbas,117 :: 		unidad=( temp_prom mod 10) + 48
$01A3	$300A			MOVLW	10
$01A4	$00F4			MOVWF	STACK_4
$01A5	$01F5			CLRF	STACK_4+1
$01A6	$0830			MOVF	_temp_prom, 0
$01A7	$00F0			MOVWF	STACK_0
$01A8	$0831			MOVF	_temp_prom+1, 0
$01A9	$00F1			MOVWF	STACK_0+1
$01AA	$2505			CALL	_div_16x16_u
$01AB	$0878			MOVF	STACK_8, 0
$01AC	$00F0			MOVWF	STACK_0
$01AD	$0879			MOVF	STACK_9, 0
$01AE	$00F1			MOVWF	STACK_1
$01AF	$3030			MOVLW	48
$01B0	$07F0			ADDWF	STACK_0, 1
$01B1	$1803			BTFSC	STATUS, C
$01B2	$0AF1			INCF	STACK_0+1, 1
$01B3	$0870			MOVF	STACK_0, 0
$01B4	$00B8			MOVWF	_unidad
;CodigoIncubadora.pbas,120 :: 		if( temp_prom>99)then
$01B5	$0831			MOVF	_temp_prom+1, 0
$01B6	$3C00			SUBLW	0
$01B7	$1D03			BTFSS	STATUS, Z
$01B8	$29BB			GOTO	L_main_1
$01B9	$0830			MOVF	_temp_prom, 0
$01BA	$3C63			SUBLW	99
$01BB	$	L_main_1:
$01BB	$1803			BTFSC	STATUS, C
$01BC	$29F8			GOTO	CodigoIncubadora_L_84
$01BD	$	CodigoIncubadora_L_83:
;CodigoIncubadora.pbas,121 :: 		flag=2
$01BD	$3002			MOVLW	2
$01BE	$00AC			MOVWF	_flag
;CodigoIncubadora.pbas,122 :: 		Lcd_Out(2,6,"T=")
$01BF	$3002			MOVLW	2
$01C0	$00D1			MOVWF	FARG_Lcd_Out
$01C1	$3006			MOVLW	6
$01C2	$00D2			MOVWF	FARG_Lcd_Out+1
$01C3	$3054			MOVLW	84
$01C4	$00BD			MOVWF	?main_Local_Text+0
$01C5	$303D			MOVLW	61
$01C6	$00BE			MOVWF	?main_Local_Text+1
$01C7	$01BF			CLRF	?main_Local_Text+2
$01C8	$303D			MOVLW	?main_Local_Text
$01C9	$00D3			MOVWF	FARG_Lcd_Out+2
$01CA	$2438			CALL	_lcd_out
;CodigoIncubadora.pbas,123 :: 		Lcd_Chr(2,8,centena )
$01CB	$3002			MOVLW	2
$01CC	$00D1			MOVWF	FARG_Lcd_Chr
$01CD	$3008			MOVLW	8
$01CE	$00D2			MOVWF	FARG_Lcd_Chr+1
$01CF	$0836			MOVF	_centena, 0
$01D0	$00D3			MOVWF	FARG_Lcd_Chr+2
$01D1	$2477			CALL	_lcd_chr
;CodigoIncubadora.pbas,124 :: 		Lcd_Chr(2,9,decena )
$01D2	$3002			MOVLW	2
$01D3	$00D1			MOVWF	FARG_Lcd_Chr
$01D4	$3009			MOVLW	9
$01D5	$00D2			MOVWF	FARG_Lcd_Chr+1
$01D6	$0837			MOVF	_decena, 0
$01D7	$00D3			MOVWF	FARG_Lcd_Chr+2
$01D8	$2477			CALL	_lcd_chr
;CodigoIncubadora.pbas,125 :: 		Lcd_Chr(2,10,unidad )
$01D9	$3002			MOVLW	2
$01DA	$00D1			MOVWF	FARG_Lcd_Chr
$01DB	$300A			MOVLW	10
$01DC	$00D2			MOVWF	FARG_Lcd_Chr+1
$01DD	$0838			MOVF	_unidad, 0
$01DE	$00D3			MOVWF	FARG_Lcd_Chr+2
$01DF	$2477			CALL	_lcd_chr
;CodigoIncubadora.pbas,126 :: 		Lcd_Out(2,11," *C")
$01E0	$3002			MOVLW	2
$01E1	$00D1			MOVWF	FARG_Lcd_Out
$01E2	$300B			MOVLW	11
$01E3	$00D2			MOVWF	FARG_Lcd_Out+1
$01E4	$3020			MOVLW	32
$01E5	$00BD			MOVWF	?main_Local_Text+0
$01E6	$302A			MOVLW	42
$01E7	$00BE			MOVWF	?main_Local_Text+1
$01E8	$3043			MOVLW	67
$01E9	$00BF			MOVWF	?main_Local_Text+2
$01EA	$01C0			CLRF	?main_Local_Text+3
$01EB	$303D			MOVLW	?main_Local_Text
$01EC	$00D3			MOVWF	FARG_Lcd_Out+2
$01ED	$2438			CALL	_lcd_out
;CodigoIncubadora.pbas,127 :: 		USART_Write (centena )
$01EE	$0836			MOVF	_centena, 0
$01EF	$00D1			MOVWF	FARG_USART_Write
$01F0	$254A			CALL	_usart_write
;CodigoIncubadora.pbas,128 :: 		USART_Write(decena)
$01F1	$0837			MOVF	_decena, 0
$01F2	$00D1			MOVWF	FARG_USART_Write
$01F3	$254A			CALL	_usart_write
;CodigoIncubadora.pbas,129 :: 		USART_Write (unidad)
$01F4	$0838			MOVF	_unidad, 0
$01F5	$00D1			MOVWF	FARG_USART_Write
$01F6	$254A			CALL	_usart_write
$01F7	$2A46			GOTO	CodigoIncubadora_L_85
;CodigoIncubadora.pbas,130 :: 		else
$01F8	$	CodigoIncubadora_L_84:
;CodigoIncubadora.pbas,132 :: 		if(flag=2) then  Lcd_Out(2,6,"         ") flag=3 end if
$01F8	$082C			MOVF	_flag, 0
$01F9	$3A02			XORLW	2
$01FA	$1D03			BTFSS	STATUS, Z
$01FB	$2A18			GOTO	CodigoIncubadora_L_87
$01FC	$	CodigoIncubadora_L_86:
$01FC	$3002			MOVLW	2
$01FD	$00D1			MOVWF	FARG_Lcd_Out
$01FE	$3006			MOVLW	6
$01FF	$00D2			MOVWF	FARG_Lcd_Out+1
$0200	$3020			MOVLW	32
$0201	$00BD			MOVWF	?main_Local_Text+0
$0202	$3020			MOVLW	32
$0203	$00BE			MOVWF	?main_Local_Text+1
$0204	$3020			MOVLW	32
$0205	$00BF			MOVWF	?main_Local_Text+2
$0206	$3020			MOVLW	32
$0207	$00C0			MOVWF	?main_Local_Text+3
$0208	$3020			MOVLW	32
$0209	$00C1			MOVWF	?main_Local_Text+4
$020A	$3020			MOVLW	32
$020B	$00C2			MOVWF	?main_Local_Text+5
$020C	$3020			MOVLW	32
$020D	$00C3			MOVWF	?main_Local_Text+6
$020E	$3020			MOVLW	32
$020F	$00C4			MOVWF	?main_Local_Text+7
$0210	$3020			MOVLW	32
$0211	$00C5			MOVWF	?main_Local_Text+8
$0212	$01C6			CLRF	?main_Local_Text+9
$0213	$303D			MOVLW	?main_Local_Text
$0214	$00D3			MOVWF	FARG_Lcd_Out+2
$0215	$2438			CALL	_lcd_out
$0216	$3003			MOVLW	3
$0217	$00AC			MOVWF	_flag
$0218	$	CodigoIncubadora_L_87:
$0218	$	CodigoIncubadora_L_88:
;CodigoIncubadora.pbas,134 :: 		Lcd_Out(2,6,"T=")
$0218	$3002			MOVLW	2
$0219	$00D1			MOVWF	FARG_Lcd_Out
$021A	$3006			MOVLW	6
$021B	$00D2			MOVWF	FARG_Lcd_Out+1
$021C	$3054			MOVLW	84
$021D	$00BD			MOVWF	?main_Local_Text+0
$021E	$303D			MOVLW	61
$021F	$00BE			MOVWF	?main_Local_Text+1
$0220	$01BF			CLRF	?main_Local_Text+2
$0221	$303D			MOVLW	?main_Local_Text
$0222	$00D3			MOVWF	FARG_Lcd_Out+2
$0223	$2438			CALL	_lcd_out
;CodigoIncubadora.pbas,135 :: 		Lcd_Chr(2,8,decena )
$0224	$3002			MOVLW	2
$0225	$00D1			MOVWF	FARG_Lcd_Chr
$0226	$3008			MOVLW	8
$0227	$00D2			MOVWF	FARG_Lcd_Chr+1
$0228	$0837			MOVF	_decena, 0
$0229	$00D3			MOVWF	FARG_Lcd_Chr+2
$022A	$2477			CALL	_lcd_chr
;CodigoIncubadora.pbas,136 :: 		Lcd_Chr(2,9,unidad)
$022B	$3002			MOVLW	2
$022C	$00D1			MOVWF	FARG_Lcd_Chr
$022D	$3009			MOVLW	9
$022E	$00D2			MOVWF	FARG_Lcd_Chr+1
$022F	$0838			MOVF	_unidad, 0
$0230	$00D3			MOVWF	FARG_Lcd_Chr+2
$0231	$2477			CALL	_lcd_chr
;CodigoIncubadora.pbas,137 :: 		Lcd_Out(2,11," *C")
$0232	$3002			MOVLW	2
$0233	$00D1			MOVWF	FARG_Lcd_Out
$0234	$300B			MOVLW	11
$0235	$00D2			MOVWF	FARG_Lcd_Out+1
$0236	$3020			MOVLW	32
$0237	$00BD			MOVWF	?main_Local_Text+0
$0238	$302A			MOVLW	42
$0239	$00BE			MOVWF	?main_Local_Text+1
$023A	$3043			MOVLW	67
$023B	$00BF			MOVWF	?main_Local_Text+2
$023C	$01C0			CLRF	?main_Local_Text+3
$023D	$303D			MOVLW	?main_Local_Text
$023E	$00D3			MOVWF	FARG_Lcd_Out+2
$023F	$2438			CALL	_lcd_out
;CodigoIncubadora.pbas,139 :: 		USART_Write(decena)
$0240	$0837			MOVF	_decena, 0
$0241	$00D1			MOVWF	FARG_USART_Write
$0242	$254A			CALL	_usart_write
;CodigoIncubadora.pbas,140 :: 		USART_Write (unidad)
$0243	$0838			MOVF	_unidad, 0
$0244	$00D1			MOVWF	FARG_USART_Write
$0245	$254A			CALL	_usart_write
;CodigoIncubadora.pbas,141 :: 		end if
$0246	$	CodigoIncubadora_L_85:
;CodigoIncubadora.pbas,143 :: 		USART_Write(10)
$0246	$300A			MOVLW	10
$0247	$00D1			MOVWF	FARG_USART_Write
$0248	$254A			CALL	_usart_write
;CodigoIncubadora.pbas,144 :: 		USART_Write(13)
$0249	$300D			MOVLW	13
$024A	$00D1			MOVWF	FARG_USART_Write
$024B	$254A			CALL	_usart_write
;CodigoIncubadora.pbas,145 :: 		muestras=0
$024C	$01AD			CLRF	_muestras, 1
;CodigoIncubadora.pbas,146 :: 		temp_ac=0
$024D	$01AE			CLRF	_temp_ac
$024E	$01AF			CLRF	_temp_ac+1
;CodigoIncubadora.pbas,147 :: 		temp_prom=0
$024F	$01B0			CLRF	_temp_prom
$0250	$01B1			CLRF	_temp_prom+1
;CodigoIncubadora.pbas,149 :: 		Delay_ms(500)
$0251	$3003			MOVLW	3
$0252	$00FC			MOVWF	STACK_12
$0253	$30FF			MOVLW	255
$0254	$00FB			MOVWF	STACK_11
$0255	$30FF			MOVLW	255
$0256	$00FA			MOVWF	STACK_10
$0257	$0BFC			DECFSZ	STACK_12, F
$0258	$2A5A			GOTO	$+2
$0259	$2A61			GOTO	$+8
$025A	$0BFB			DECFSZ	STACK_11, F
$025B	$2A5D			GOTO	$+2
$025C	$2A60			GOTO	$+4
$025D	$0BFA			DECFSZ	STACK_10, F
$025E	$2A5D			GOTO	$-1
$025F	$2A5A			GOTO	$-5
$0260	$2A57			GOTO	$-9
$0261	$308C			MOVLW	140
$0262	$00FB			MOVWF	STACK_11
$0263	$30FF			MOVLW	255
$0264	$00FA			MOVWF	STACK_10
$0265	$0BFB			DECFSZ	STACK_11, F
$0266	$2A68			GOTO	$+2
$0267	$2A6B			GOTO	$+4
$0268	$0BFA			DECFSZ	STACK_10, F
$0269	$2A68			GOTO	$-1
$026A	$2A65			GOTO	$-5
$026B	$30A1			MOVLW	161
$026C	$00FA			MOVWF	STACK_10
$026D	$0BFA			DECFSZ	STACK_10, F
$026E	$2A6D			GOTO	$-1
$026F	$0000			NOP
$0270	$292A			GOTO	CodigoIncubadora_L_65
;CodigoIncubadora.pbas,151 :: 		wend
$0271	$2A71			GOTO	$
