;  Assembly code generated by mikroVirtualMachine - V. 5.0.0.3
;  Date/Time: 18/01/2011 1:02:07
;  Info: http://www.mikroe.com


; ADDRESS	OPCODE	ASM
; ----------------------------------------------
$0000	$28B5			GOTO	_main
$0274	$	_usart_data_ready:
;USART_c67.ppas,48 :: 		
;USART_c67.ppas,50 :: 		
$0274	$1303			BCF	STATUS, RP1
$0275	$1283			BCF	STATUS, RP0
$0276	$080C			MOVF	PIR1, 0
$0277	$00F1			MOVWF	STACK_1
$0278	$3000			MOVLW	0
$0279	$1AF1			BTFSC	STACK_1, 5
$027A	$3001			MOVLW	1
$027B	$00F1			MOVWF	STACK_1
$027C	$0871			MOVF	STACK_1, 0
$027D	$00B5			MOVWF	_usart_data_ready_local_result
$027E	$	USART_c67_L_18:
;USART_c67.ppas,51 :: 		
$027E	$0835			MOVF	_usart_data_ready_local_result, 0
$027F	$00F0			MOVWF	STACK_0
$0280	$0008			RETURN
$023E	$	_usart_read:
;USART_c67.ppas,54 :: 		
;USART_c67.ppas,55 :: 		
$023E	$1303			BCF	STATUS, RP1
$023F	$1283			BCF	STATUS, RP0
$0240	$081A			MOVF	RCREG, 0
$0241	$00B5			MOVWF	_usart_read_local_result
;USART_c67.ppas,61 :: 		
$0242	$0818			MOVF	RCSTA, 0
$0243	$00F1			MOVWF	STACK_1
$0244	$3000			MOVLW	0
$0245	$18F1			BTFSC	STACK_1, 1
$0246	$3001			MOVLW	1
$0247	$00F1			MOVWF	STACK_1
$0248	$0871			MOVF	STACK_1, 0
$0249	$3A01			XORLW	1
$024A	$1D03			BTFSS	STATUS, Z
$024B	$2A4E			GOTO	USART_c67_L_21
$024C	$	USART_c67_L_20:
;USART_c67.ppas,63 :: 		
$024C	$1218			BCF	RCSTA, 4
$024D	$	USART_c67_L_24:
;USART_c67.ppas,64 :: 		
$024D	$	USART_c67_L_25:
$024D	$1618			BSF	RCSTA, 4
$024E	$	USART_c67_L_26:
;USART_c67.ppas,65 :: 		
$024E	$	USART_c67_L_21:
$024E	$	USART_c67_L_22:
$024E	$	USART_c67_L_19:
;USART_c67.ppas,66 :: 		
$024E	$0835			MOVF	_usart_read_local_result, 0
$024F	$00F0			MOVWF	STACK_0
$0250	$0008			RETURN
$0004	$	_interrupt:
$0004	$00FF			MOVWF	STACK_15
$0005	$0E03			SWAPF	STATUS, 0
$0006	$0183			CLRF	STATUS
$0007	$00B3			MOVWF	?saveSTATUS
$0008	$0804			MOVF	FSR, 0
$0009	$00B2			MOVWF	?saveFSR
$000A	$080A			MOVF	PCLATH, 0
$000B	$00B4			MOVWF	?savePCLATH
$000C	$018A			CLRF	PCLATH
$000D	$0872			MOVF	STACK_2, 0
$000E	$00BF			MOVWF	STSAVED_2
$000F	$0871			MOVF	STACK_1, 0
$0010	$00BE			MOVWF	STSAVED_1
$0011	$0870			MOVF	STACK_0, 0
$0012	$00BD			MOVWF	STSAVED_0
;CodigoCalentador.pbas,8 :: 		sub procedure interrupt()
;CodigoCalentador.pbas,10 :: 		if(PIR1.RCIF=1)then
$0013	$3000			MOVLW	0
$0014	$1A8C			BTFSC	PIR1, 5
$0015	$3001			MOVLW	1
$0016	$00F2			MOVWF	STACK_2
$0017	$0872			MOVF	STACK_2, 0
$0018	$3A01			XORLW	1
$0019	$1D03			BTFSS	STATUS, Z
$001A	$284B			GOTO	CodigoCalentador_L_2
$001B	$	CodigoCalentador_L_1:
;CodigoCalentador.pbas,11 :: 		if Usart_Data_Ready = 1 then
$001B	$2274			CALL	_usart_data_ready
$001C	$0870			MOVF	STACK_0, 0
$001D	$3A01			XORLW	1
$001E	$1D03			BTFSS	STATUS, Z
$001F	$2848			GOTO	CodigoCalentador_L_5
$0020	$	CodigoCalentador_L_4:
;CodigoCalentador.pbas,12 :: 		recibido = Usart_Read
$0020	$223E			CALL	_usart_read
$0021	$0870			MOVF	STACK_0, 0
$0022	$00A0			MOVWF	_recibido
;CodigoCalentador.pbas,13 :: 		if i=1 then
$0023	$0821			MOVF	_i, 0
$0024	$3A01			XORLW	1
$0025	$1D03			BTFSS	STATUS, Z
$0026	$282A			GOTO	CodigoCalentador_L_8
$0027	$	CodigoCalentador_L_7:
;CodigoCalentador.pbas,14 :: 		i=0
$0027	$01A1			CLRF	_i, 1
;CodigoCalentador.pbas,15 :: 		intensidad=recibido
$0028	$0820			MOVF	_recibido, 0
$0029	$00A2			MOVWF	_intensidad
$002A	$	CodigoCalentador_L_8:
;CodigoCalentador.pbas,16 :: 		end if
$002A	$	CodigoCalentador_L_9:
;CodigoCalentador.pbas,17 :: 		if i=2 then
$002A	$0821			MOVF	_i, 0
$002B	$3A02			XORLW	2
$002C	$1D03			BTFSS	STATUS, Z
$002D	$2838			GOTO	CodigoCalentador_L_11
$002E	$	CodigoCalentador_L_10:
;CodigoCalentador.pbas,18 :: 		i=0
$002E	$01A1			CLRF	_i, 1
;CodigoCalentador.pbas,19 :: 		if recibido = 1 then
$002F	$0820			MOVF	_recibido, 0
$0030	$3A01			XORLW	1
$0031	$1D03			BTFSS	STATUS, Z
$0032	$2836			GOTO	CodigoCalentador_L_14
$0033	$	CodigoCalentador_L_13:
;CodigoCalentador.pbas,20 :: 		portb.4=0
$0033	$1206			BCF	PORTB, 4
$0034	$	CodigoCalentador_L_17:
;CodigoCalentador.pbas,21 :: 		porta.1=0
$0034	$1085			BCF	PORTA, 1
$0035	$	CodigoCalentador_L_19:
$0035	$2838			GOTO	CodigoCalentador_L_15
;CodigoCalentador.pbas,22 :: 		else
$0036	$	CodigoCalentador_L_14:
;CodigoCalentador.pbas,23 :: 		portb.4=1
$0036	$	CodigoCalentador_L_20:
$0036	$1606			BSF	PORTB, 4
$0037	$	CodigoCalentador_L_21:
;CodigoCalentador.pbas,24 :: 		porta.1=1
$0037	$	CodigoCalentador_L_22:
$0037	$1485			BSF	PORTA, 1
$0038	$	CodigoCalentador_L_23:
;CodigoCalentador.pbas,25 :: 		end if
$0038	$	CodigoCalentador_L_15:
$0038	$	CodigoCalentador_L_11:
;CodigoCalentador.pbas,26 :: 		end if
$0038	$	CodigoCalentador_L_12:
;CodigoCalentador.pbas,27 :: 		if i=0 then
$0038	$0821			MOVF	_i, 0
$0039	$3A00			XORLW	0
$003A	$1D03			BTFSS	STATUS, Z
$003B	$2848			GOTO	CodigoCalentador_L_25
$003C	$	CodigoCalentador_L_24:
;CodigoCalentador.pbas,28 :: 		if recibido=0xA0 then
$003C	$0820			MOVF	_recibido, 0
$003D	$3AA0			XORLW	160
$003E	$1D03			BTFSS	STATUS, Z
$003F	$2842			GOTO	CodigoCalentador_L_28
$0040	$	CodigoCalentador_L_27:
;CodigoCalentador.pbas,29 :: 		i=1
$0040	$3001			MOVLW	1
$0041	$00A1			MOVWF	_i
$0042	$	CodigoCalentador_L_28:
;CodigoCalentador.pbas,30 :: 		end if
$0042	$	CodigoCalentador_L_29:
;CodigoCalentador.pbas,31 :: 		if recibido=0xB0 then
$0042	$0820			MOVF	_recibido, 0
$0043	$3AB0			XORLW	176
$0044	$1D03			BTFSS	STATUS, Z
$0045	$2848			GOTO	CodigoCalentador_L_31
$0046	$	CodigoCalentador_L_30:
;CodigoCalentador.pbas,32 :: 		i=2   '0xB0
$0046	$3002			MOVLW	2
$0047	$00A1			MOVWF	_i
$0048	$	CodigoCalentador_L_31:
;CodigoCalentador.pbas,33 :: 		end if
$0048	$	CodigoCalentador_L_32:
$0048	$	CodigoCalentador_L_25:
;CodigoCalentador.pbas,34 :: 		end if
$0048	$	CodigoCalentador_L_26:
$0048	$	CodigoCalentador_L_5:
;CodigoCalentador.pbas,36 :: 		end if
$0048	$	CodigoCalentador_L_6:
;CodigoCalentador.pbas,37 :: 		PIR1.RCIF=0   ' Si el dato a llegado limpio la bandera de recepcion
$0048	$128C			BCF	PIR1, 5
$0049	$	CodigoCalentador_L_34:
;CodigoCalentador.pbas,38 :: 		PIE1.RCIE=1   ' Habilitar nuevamente la interrupcion por USART
$0049	$	CodigoCalentador_L_35:
$0049	$1683			BSF	STATUS, RP0
$004A	$168C			BSF	PIE1, 5
$004B	$	CodigoCalentador_L_36:
$004B	$	CodigoCalentador_L_2:
;CodigoCalentador.pbas,39 :: 		end if
$004B	$	CodigoCalentador_L_3:
;CodigoCalentador.pbas,41 :: 		if(INTCON.INTF=1)then
$004B	$1303			BCF	STATUS, RP1
$004C	$1683			BSF	STATUS, RP0
$004D	$3000			MOVLW	0
$004E	$188B			BTFSC	INTCON, 1
$004F	$3001			MOVLW	1
$0050	$00F2			MOVWF	STACK_2
$0051	$0872			MOVF	STACK_2, 0
$0052	$3A01			XORLW	1
$0053	$1D03			BTFSS	STATUS, Z
$0054	$2899			GOTO	CodigoCalentador_L_38
$0055	$	CodigoCalentador_L_37:
;CodigoCalentador.pbas,42 :: 		if(intensidad > 0)then
$0055	$1283			BCF	STATUS, RP0
$0056	$0822			MOVF	_intensidad, 0
$0057	$3C00			SUBLW	0
$0058	$1803			BTFSC	STATUS, C
$0059	$2896			GOTO	CodigoCalentador_L_41
$005A	$	CodigoCalentador_L_40:
;CodigoCalentador.pbas,43 :: 		PORTB.5=0
$005A	$1286			BCF	PORTB, 5
$005B	$	CodigoCalentador_L_44:
;CodigoCalentador.pbas,46 :: 		case 1
$005B	$	CodigoCalentador_L_47:
$005B	$0822			MOVF	_intensidad, 0
$005C	$3A01			XORLW	1
$005D	$1D03			BTFSS	STATUS, Z
$005E	$2862			GOTO	CodigoCalentador_L_48
$005F	$	CodigoCalentador_L_46:
;CodigoCalentador.pbas,47 :: 		TMR0=240
$005F	$30F0			MOVLW	240
$0060	$0081			MOVWF	TMR0
$0061	$2893			GOTO	CodigoCalentador_L_45
$0062	$	CodigoCalentador_L_48:
;CodigoCalentador.pbas,48 :: 		case 2
$0062	$	CodigoCalentador_L_50:
$0062	$0822			MOVF	_intensidad, 0
$0063	$3A02			XORLW	2
$0064	$1D03			BTFSS	STATUS, Z
$0065	$2869			GOTO	CodigoCalentador_L_51
$0066	$	CodigoCalentador_L_49:
;CodigoCalentador.pbas,49 :: 		TMR0=225
$0066	$30E1			MOVLW	225
$0067	$0081			MOVWF	TMR0
$0068	$2893			GOTO	CodigoCalentador_L_45
$0069	$	CodigoCalentador_L_51:
;CodigoCalentador.pbas,50 :: 		case 3
$0069	$	CodigoCalentador_L_53:
$0069	$0822			MOVF	_intensidad, 0
$006A	$3A03			XORLW	3
$006B	$1D03			BTFSS	STATUS, Z
$006C	$2870			GOTO	CodigoCalentador_L_54
$006D	$	CodigoCalentador_L_52:
;CodigoCalentador.pbas,51 :: 		TMR0=209
$006D	$30D1			MOVLW	209
$006E	$0081			MOVWF	TMR0
$006F	$2893			GOTO	CodigoCalentador_L_45
$0070	$	CodigoCalentador_L_54:
;CodigoCalentador.pbas,52 :: 		case 4
$0070	$	CodigoCalentador_L_56:
$0070	$0822			MOVF	_intensidad, 0
$0071	$3A04			XORLW	4
$0072	$1D03			BTFSS	STATUS, Z
$0073	$2877			GOTO	CodigoCalentador_L_57
$0074	$	CodigoCalentador_L_55:
;CodigoCalentador.pbas,53 :: 		TMR0=193
$0074	$30C1			MOVLW	193
$0075	$0081			MOVWF	TMR0
$0076	$2893			GOTO	CodigoCalentador_L_45
$0077	$	CodigoCalentador_L_57:
;CodigoCalentador.pbas,54 :: 		case 5
$0077	$	CodigoCalentador_L_59:
$0077	$0822			MOVF	_intensidad, 0
$0078	$3A05			XORLW	5
$0079	$1D03			BTFSS	STATUS, Z
$007A	$287E			GOTO	CodigoCalentador_L_60
$007B	$	CodigoCalentador_L_58:
;CodigoCalentador.pbas,55 :: 		TMR0=178
$007B	$30B2			MOVLW	178
$007C	$0081			MOVWF	TMR0
$007D	$2893			GOTO	CodigoCalentador_L_45
$007E	$	CodigoCalentador_L_60:
;CodigoCalentador.pbas,56 :: 		case 6
$007E	$	CodigoCalentador_L_62:
$007E	$0822			MOVF	_intensidad, 0
$007F	$3A06			XORLW	6
$0080	$1D03			BTFSS	STATUS, Z
$0081	$2885			GOTO	CodigoCalentador_L_63
$0082	$	CodigoCalentador_L_61:
;CodigoCalentador.pbas,57 :: 		TMR0=162
$0082	$30A2			MOVLW	162
$0083	$0081			MOVWF	TMR0
$0084	$2893			GOTO	CodigoCalentador_L_45
$0085	$	CodigoCalentador_L_63:
;CodigoCalentador.pbas,58 :: 		case 7
$0085	$	CodigoCalentador_L_65:
$0085	$0822			MOVF	_intensidad, 0
$0086	$3A07			XORLW	7
$0087	$1D03			BTFSS	STATUS, Z
$0088	$288C			GOTO	CodigoCalentador_L_66
$0089	$	CodigoCalentador_L_64:
;CodigoCalentador.pbas,59 :: 		TMR0=146
$0089	$3092			MOVLW	146
$008A	$0081			MOVWF	TMR0
$008B	$2893			GOTO	CodigoCalentador_L_45
$008C	$	CodigoCalentador_L_66:
;CodigoCalentador.pbas,60 :: 		case 8
$008C	$	CodigoCalentador_L_68:
$008C	$0822			MOVF	_intensidad, 0
$008D	$3A08			XORLW	8
$008E	$1D03			BTFSS	STATUS, Z
$008F	$2893			GOTO	CodigoCalentador_L_69
$0090	$	CodigoCalentador_L_67:
;CodigoCalentador.pbas,61 :: 		TMR0=131
$0090	$3083			MOVLW	131
$0091	$0081			MOVWF	TMR0
$0092	$2893			GOTO	CodigoCalentador_L_45
$0093	$	CodigoCalentador_L_69:
$0093	$	CodigoCalentador_L_45:
;CodigoCalentador.pbas,63 :: 		INTCON.T0IF=0
$0093	$110B			BCF	INTCON, 2
$0094	$	CodigoCalentador_L_71:
;CodigoCalentador.pbas,64 :: 		INTCON.T0IE=1
$0094	$	CodigoCalentador_L_72:
$0094	$168B			BSF	INTCON, 5
$0095	$	CodigoCalentador_L_73:
$0095	$2897			GOTO	CodigoCalentador_L_42
;CodigoCalentador.pbas,65 :: 		else
$0096	$	CodigoCalentador_L_41:
;CodigoCalentador.pbas,66 :: 		PORTB.5=1
$0096	$	CodigoCalentador_L_74:
$0096	$1686			BSF	PORTB, 5
$0097	$	CodigoCalentador_L_75:
;CodigoCalentador.pbas,67 :: 		end if
$0097	$	CodigoCalentador_L_42:
;CodigoCalentador.pbas,68 :: 		INTCON.INTF=0
$0097	$108B			BCF	INTCON, 1
$0098	$	CodigoCalentador_L_77:
;CodigoCalentador.pbas,69 :: 		INTCON.INTE =1
$0098	$	CodigoCalentador_L_78:
$0098	$160B			BSF	INTCON, 4
$0099	$	CodigoCalentador_L_79:
$0099	$	CodigoCalentador_L_38:
;CodigoCalentador.pbas,71 :: 		end if
$0099	$	CodigoCalentador_L_39:
;CodigoCalentador.pbas,73 :: 		if(INTCON.T0IF =1)then
$0099	$1303			BCF	STATUS, RP1
$009A	$1283			BCF	STATUS, RP0
$009B	$3000			MOVLW	0
$009C	$190B			BTFSC	INTCON, 2
$009D	$3001			MOVLW	1
$009E	$00F2			MOVWF	STACK_2
$009F	$0872			MOVF	STACK_2, 0
$00A0	$3A01			XORLW	1
$00A1	$1D03			BTFSS	STATUS, Z
$00A2	$28A6			GOTO	CodigoCalentador_L_81
$00A3	$	CodigoCalentador_L_80:
;CodigoCalentador.pbas,74 :: 		PORTB.5=1
$00A3	$	CodigoCalentador_L_83:
$00A3	$1686			BSF	PORTB, 5
$00A4	$	CodigoCalentador_L_84:
;CodigoCalentador.pbas,75 :: 		INTCON.T0IF=0
$00A4	$110B			BCF	INTCON, 2
$00A5	$	CodigoCalentador_L_86:
;CodigoCalentador.pbas,76 :: 		INTCON.T0IE=0
$00A5	$128B			BCF	INTCON, 5
$00A6	$	CodigoCalentador_L_88:
$00A6	$	CodigoCalentador_L_81:
;CodigoCalentador.pbas,77 :: 		end if
$00A6	$	CodigoCalentador_L_82:
$00A6	$	CodigoCalentador_L_0:
$00A6	$	L_Interrupt_end:
$00A6	$083F			MOVF	STSAVED_2, 0
$00A7	$00F2			MOVWF	STACK_2
$00A8	$083E			MOVF	STSAVED_1, 0
$00A9	$00F1			MOVWF	STACK_1
$00AA	$083D			MOVF	STSAVED_0, 0
$00AB	$00F0			MOVWF	STACK_0
$00AC	$0834			MOVF	?savePCLATH, 0
$00AD	$008A			MOVWF	PCLATH
$00AE	$0832			MOVF	?saveFSR, 0
$00AF	$0084			MOVWF	FSR
$00B0	$0E33			SWAPF	?saveSTATUS, 0
$00B1	$0083			MOVWF	STATUS
$00B2	$0EFF			SWAPF	STACK_15, 1
$00B3	$0E7F			SWAPF	STACK_15, 0
$00B4	$0009			RETFIE
$0281	$	_delay_22us:
;delays.pbas,17 :: 		sub procedure Delay_22us()
;delays.pbas,18 :: 		Delay_us(22)
$0281	$3007			MOVLW	7
$0282	$1303			BCF	STATUS, RP1
$0283	$1283			BCF	STATUS, RP0
$0284	$00FA			MOVWF	STACK_10
$0285	$0BFA			DECFSZ	STACK_10, F
$0286	$2A85			GOTO	$-1
$0287	$	delays_L_3:
$0287	$0008			RETURN
$0263	$	_div_8x8_u:
$0263	$1303			BCF	STATUS, RP1
$0264	$1283			BCF	STATUS, RP0
;math.ppas,88 :: 		
;math.ppas,90 :: 		
$0265	$01F8			CLRF	STACK_8, F
;math.ppas,91 :: 		
$0266	$3008			MOVLW	8
;math.ppas,92 :: 		
$0267	$00FC			MOVWF	STACK_12
;math.ppas,93 :: 		
$0268	$0D70			RLF	STACK_0, W
;math.ppas,94 :: 		
$0269	$0DF8			RLF	STACK_8, F
;math.ppas,95 :: 		
$026A	$0874			MOVF	STACK_4, W
;math.ppas,96 :: 		
$026B	$02F8			SUBWF	STACK_8, F
;math.ppas,97 :: 		
$026C	$1803			BTFSC	STATUS, C
;math.ppas,98 :: 		
$026D	$2A70			GOTO	$+3
;math.ppas,99 :: 		
$026E	$07F8			ADDWF	STACK_8, F
;math.ppas,100 :: 		
$026F	$1003			BCF	STATUS, C
;math.ppas,101 :: 		
$0270	$0DF0			RLF	STACK_0, F
;math.ppas,102 :: 		
$0271	$0BFC			DECFSZ	STACK_12, F
;math.ppas,103 :: 		
$0272	$2A68			GOTO	$-10
;math.ppas,104 :: 		
$0273	$	math_L_2:
;math.ppas,105 :: 		
$0273	$0008			RETURN
$0251	$	_usart_write:
;USART_c67.ppas,40 :: 		
;USART_c67.ppas,42 :: 		
$0251	$	USART_c67_L_14:
$0251	$1303			BCF	STATUS, RP1
$0252	$1683			BSF	STATUS, RP0
$0253	$0818			MOVF	TXSTA, 0
$0254	$00F1			MOVWF	STACK_1
$0255	$3000			MOVLW	0
$0256	$18F1			BTFSC	STACK_1, 1
$0257	$3001			MOVLW	1
$0258	$00F1			MOVWF	STACK_1
$0259	$0871			MOVF	STACK_1, 0
$025A	$3A00			XORLW	0
$025B	$1D03			BTFSS	STATUS, Z
$025C	$2A5F			GOTO	USART_c67_L_15
;USART_c67.ppas,43 :: 		
$025D	$0000			NOP
$025E	$2A51			GOTO	USART_c67_L_14
$025F	$	USART_c67_L_15:
;USART_c67.ppas,44 :: 		
$025F	$1283			BCF	STATUS, RP0
$0260	$083C			MOVF	FARG_USART_Write, 0
$0261	$0099			MOVWF	TXREG
$0262	$	USART_c67_L_12:
;USART_c67.ppas,45 :: 		
$0262	$0008			RETURN
$019A	$	_adc_read:
;ADClib_88X.ppas,9 :: 		
;ADClib_88X.ppas,10 :: 		
$019A	$30C0			MOVLW	192
$019B	$1303			BCF	STATUS, RP1
$019C	$1283			BCF	STATUS, RP0
$019D	$009F			MOVWF	ADCON0
;ADClib_88X.ppas,11 :: 		
$019E	$0838			MOVF	FARG_Adc_Read, 0
$019F	$00F0			MOVWF	STACK_0
$01A0	$0DF0			RLF	STACK_0, 1
$01A1	$1070			BCF	STACK_0, 0
$01A2	$0DF0			RLF	STACK_0, 1
$01A3	$1070			BCF	STACK_0, 0
$01A4	$0870			MOVF	STACK_0, 0
$01A5	$049F			IORWF	ADCON0, 1
;ADClib_88X.ppas,12 :: 		
$01A6	$	ADClib_88X_L_1:
$01A6	$1683			BSF	STATUS, RP0
$01A7	$179F			BSF	ADCON1, 7
$01A8	$	ADClib_88X_L_2:
;ADClib_88X.ppas,15 :: 		
$01A8	$	ADClib_88X_L_3:
$01A8	$1283			BCF	STATUS, RP0
$01A9	$141F			BSF	ADCON0, 0
$01AA	$	ADClib_88X_L_4:
;ADClib_88X.ppas,18 :: 		
$01AA	$2281			CALL	_delay_22us
;ADClib_88X.ppas,21 :: 		
$01AB	$	ADClib_88X_L_5:
$01AB	$149F			BSF	ADCON0, 1
$01AC	$	ADClib_88X_L_6:
;ADClib_88X.ppas,24 :: 		
$01AC	$	ADClib_88X_L_8:
$01AC	$081F			MOVF	ADCON0, 0
$01AD	$00F2			MOVWF	STACK_2
$01AE	$3000			MOVLW	0
$01AF	$18F2			BTFSC	STACK_2, 1
$01B0	$3001			MOVLW	1
$01B1	$00F2			MOVWF	STACK_2
$01B2	$0872			MOVF	STACK_2, 0
$01B3	$3A00			XORLW	0
$01B4	$1D03			BTFSS	STATUS, Z
$01B5	$29AC			GOTO	ADClib_88X_L_8
;ADClib_88X.ppas,26 :: 		
$01B6	$	ADClib_88X_L_9:
;ADClib_88X.ppas,29 :: 		
$01B6	$101F			BCF	ADCON0, 0
$01B7	$	ADClib_88X_L_13:
;ADClib_88X.ppas,32 :: 		
$01B7	$081E			MOVF	ADRESH, 0
$01B8	$00F2			MOVWF	STACK_2
$01B9	$01F3			CLRF	STACK_2+1
$01BA	$0872			MOVF	STACK_2, 0
$01BB	$00F3			MOVWF	STACK_2+1
$01BC	$01F2			CLRF	STACK_2
$01BD	$1683			BSF	STATUS, RP0
$01BE	$081E			MOVF	ADRESL, 0
$01BF	$0472			IORWF	STACK_2, 0
$01C0	$1283			BCF	STATUS, RP0
$01C1	$00B9			MOVWF	_adc_read_local_result
$01C2	$0873			MOVF	STACK_2+1, 0
$01C3	$00BA			MOVWF	_adc_read_local_result+1
$01C4	$3000			MOVLW	0
$01C5	$04BA			IORWF	_adc_read_local_result+1, 1
$01C6	$	ADClib_88X_L_0:
;ADClib_88X.ppas,33 :: 		
$01C6	$0839			MOVF	_adc_read_local_result, 0
$01C7	$00F0			MOVWF	STACK_0
$01C8	$083A			MOVF	_adc_read_local_result+1, 0
$01C9	$00F1			MOVWF	STACK_0+1
$01CA	$0008			RETURN
$0168	$	_bytetostr:
;conv.ppas,8 :: 		
;conv.ppas,9 :: 		
$0168	$3001			MOVLW	1
$0169	$1303			BCF	STATUS, RP1
$016A	$1283			BCF	STATUS, RP0
$016B	$00BA			MOVWF	_bytetostr_local_len
;conv.ppas,10 :: 		
$016C	$0838			MOVF	FARG_ByteToStr, 0
$016D	$3C09			SUBLW	9
$016E	$1803			BTFSC	STATUS, C
$016F	$2971			GOTO	conv_L_2
$0170	$	conv_L_1:
;conv.ppas,11 :: 		
$0170	$0ABA			INCF	_bytetostr_local_len, 1
$0171	$	conv_L_2:
$0171	$	conv_L_3:
;conv.ppas,12 :: 		
$0171	$0838			MOVF	FARG_ByteToStr, 0
$0172	$3C63			SUBLW	99
$0173	$1803			BTFSC	STATUS, C
$0174	$2976			GOTO	conv_L_5
$0175	$	conv_L_4:
;conv.ppas,13 :: 		
$0175	$0ABA			INCF	_bytetostr_local_len, 1
$0176	$	conv_L_5:
$0176	$	conv_L_6:
;conv.ppas,14 :: 		
$0176	$0839			MOVF	FARG_ByteToStr+1, 0
$0177	$0084			MOVWF	FSR
$0178	$3020			MOVLW	32
$0179	$0080			MOVWF	INDF
$017A	$0A84			INCF	FSR, 1
$017B	$0080			MOVWF	INDF
$017C	$0A84			INCF	FSR, 1
$017D	$0080			MOVWF	INDF
$017E	$0A84			INCF	FSR, 1
$017F	$0180			CLRF	INDF
;conv.ppas,15 :: 		
$0180	$0384			DECF	FSR, 1
;conv.ppas,17 :: 		
$0181	$	conv_L_9:
$0181	$083A			MOVF	_bytetostr_local_len, 0
$0182	$3C00			SUBLW	0
$0183	$1803			BTFSC	STATUS, C
$0184	$2999			GOTO	conv_L_10
;conv.ppas,19 :: 		
$0185	$300A			MOVLW	10
$0186	$00F4			MOVWF	STACK_4
$0187	$0838			MOVF	FARG_ByteToStr, 0
$0188	$00F0			MOVWF	STACK_0
$0189	$2263			CALL	_div_8x8_u
$018A	$0878			MOVF	STACK_8, 0
$018B	$00F0			MOVWF	STACK_0
$018C	$3030			MOVLW	48
$018D	$0770			ADDWF	STACK_0, 0
$018E	$0080			MOVWF	INDF
;conv.ppas,20 :: 		
;conv.ppas,21 :: 		
$018F	$0384			DECF	FSR, 1
;conv.ppas,22 :: 		
$0190	$300A			MOVLW	10
$0191	$00F4			MOVWF	STACK_4
$0192	$0838			MOVF	FARG_ByteToStr, 0
$0193	$00F0			MOVWF	STACK_0
$0194	$2263			CALL	_div_8x8_u
$0195	$0870			MOVF	STACK_0, 0
$0196	$00B8			MOVWF	FARG_ByteToStr
;conv.ppas,23 :: 		
$0197	$03BA			DECF	_bytetostr_local_len, 1
;conv.ppas,24 :: 		
$0198	$2981			GOTO	conv_L_9
$0199	$	conv_L_10:
$0199	$	conv_L_0:
;conv.ppas,26 :: 		
$0199	$0008			RETURN
$0213	$	_usart_write_text:
;USART_c67.ppas,121 :: 		
;USART_c67.ppas,122 :: 		
$0213	$1303			BCF	STATUS, RP1
$0214	$1283			BCF	STATUS, RP0
$0215	$01B9			CLRF	_usart_write_text_local_i, 1
;USART_c67.ppas,123 :: 		
$0216	$0838			MOVF	FARG_Usart_Write_Text, 0
$0217	$0084			MOVWF	FSR
$0218	$0800			MOVF	INDF, 0
$0219	$00BA			MOVWF	_usart_write_text_local_data
;USART_c67.ppas,124 :: 		
$021A	$	USART_c67_L_47:
$021A	$083A			MOVF	_usart_write_text_local_data, 0
$021B	$3A00			XORLW	0
$021C	$1903			BTFSC	STATUS, Z
$021D	$2A28			GOTO	USART_c67_L_48
;USART_c67.ppas,126 :: 		
$021E	$083A			MOVF	_usart_write_text_local_data, 0
$021F	$00BC			MOVWF	FARG_USART_Write
$0220	$2251			CALL	_usart_write
;USART_c67.ppas,127 :: 		
$0221	$0AB9			INCF	_usart_write_text_local_i, 1
;USART_c67.ppas,128 :: 		
$0222	$0839			MOVF	_usart_write_text_local_i, 0
$0223	$0738			ADDWF	FARG_Usart_Write_Text, 0
$0224	$0084			MOVWF	FSR
$0225	$0800			MOVF	INDF, 0
$0226	$00BA			MOVWF	_usart_write_text_local_data
;USART_c67.ppas,129 :: 		
$0227	$2A1A			GOTO	USART_c67_L_47
$0228	$	USART_c67_L_48:
$0228	$	USART_c67_L_45:
;USART_c67.ppas,130 :: 		
$0228	$0008			RETURN
$0229	$	_usart_init:
;USART_c67.ppas,22 :: 		
;USART_c67.ppas,24 :: 		
$0229	$	USART_c67_L_1:
$0229	$1303			BCF	STATUS, RP1
$022A	$1683			BSF	STATUS, RP0
$022B	$1698			BSF	TXSTA, 5
$022C	$	USART_c67_L_2:
;USART_c67.ppas,25 :: 		
$022C	$3090			MOVLW	144
$022D	$1283			BCF	STATUS, RP0
$022E	$0098			MOVWF	RCSTA
;USART_c67.ppas,31 :: 		
$022F	$	USART_c67_L_3:
$022F	$1683			BSF	STATUS, RP0
$0230	$1787			BSF	TRISC, 7
$0231	$	USART_c67_L_4:
;USART_c67.ppas,32 :: 		
$0231	$1307			BCF	TRISC, 6
$0232	$	USART_c67_L_6:
;USART_c67.ppas,35 :: 		
$0232	$	USART_c67_L_8:
$0232	$1283			BCF	STATUS, RP0
$0233	$080C			MOVF	PIR1, 0
$0234	$00F1			MOVWF	STACK_1
$0235	$3000			MOVLW	0
$0236	$1AF1			BTFSC	STACK_1, 5
$0237	$3001			MOVLW	1
$0238	$00F1			MOVWF	STACK_1
$0239	$0871			MOVF	STACK_1, 0
$023A	$3A01			XORLW	1
$023B	$1903			BTFSC	STATUS, Z
$023C	$2A32			GOTO	USART_c67_L_8
;USART_c67.ppas,36 :: 		
$023D	$	USART_c67_L_9:
$023D	$	USART_c67_L_0:
;USART_c67.ppas,37 :: 		
$023D	$0008			RETURN
$01CB	$	_mul_16x16_u:
$01CB	$1303			BCF	STATUS, RP1
$01CC	$1283			BCF	STATUS, RP0
;math.ppas,42 :: 		
;math.ppas,44 :: 		
$01CD	$01FB			CLRF	STACK_11
;math.ppas,45 :: 		
$01CE	$01FA			CLRF	STACK_10
;math.ppas,46 :: 		
$01CF	$01F9			CLRF	STACK_9
;math.ppas,47 :: 		
$01D0	$3080			MOVLW	128
;math.ppas,48 :: 		
$01D1	$00F8			MOVWF	STACK_8
;math.ppas,49 :: 		
$01D2	$0CF1			RRF	STACK_1, F
;math.ppas,50 :: 		
$01D3	$0CF0			RRF	STACK_0, F
;math.ppas,51 :: 		
$01D4	$1C03			BTFSS	STATUS, C
;math.ppas,52 :: 		
$01D5	$29DF			GOTO	$+10
;math.ppas,53 :: 		
$01D6	$0874			MOVF	STACK_4, W
;math.ppas,54 :: 		
$01D7	$07F9			ADDWF	STACK_9, F
;math.ppas,55 :: 		
$01D8	$0875			MOVF	STACK_5, W
;math.ppas,56 :: 		
$01D9	$1803			BTFSC	STATUS, C
;math.ppas,57 :: 		
$01DA	$0F75			INCFSZ	STACK_5, W
;math.ppas,58 :: 		
$01DB	$07FA			ADDWF	STACK_10, F
;math.ppas,59 :: 		
$01DC	$1803			BTFSC	STATUS, C
;math.ppas,60 :: 		
$01DD	$0AFB			INCF	STACK_11, F
;math.ppas,61 :: 		
$01DE	$1003			BCF	STATUS, C
;math.ppas,62 :: 		
$01DF	$1FF0			BTFSS	STACK_0, 7
;math.ppas,63 :: 		
$01E0	$29E7			GOTO	$+7
;math.ppas,64 :: 		
$01E1	$0874			MOVF	STACK_4, W
;math.ppas,65 :: 		
$01E2	$07FA			ADDWF	STACK_10, F
;math.ppas,66 :: 		
$01E3	$0875			MOVF	STACK_5, W
;math.ppas,67 :: 		
$01E4	$1803			BTFSC	STATUS, C
;math.ppas,68 :: 		
$01E5	$0F75			INCFSZ	STACK_5, W
;math.ppas,69 :: 		
$01E6	$07FB			ADDWF	STACK_11, F
;math.ppas,70 :: 		
$01E7	$0CFB			RRF	STACK_11, F
;math.ppas,71 :: 		
$01E8	$0CFA			RRF	STACK_10, F
;math.ppas,72 :: 		
$01E9	$0CF9			RRF	STACK_9, F
;math.ppas,73 :: 		
$01EA	$0CF8			RRF	STACK_8, F
;math.ppas,74 :: 		
$01EB	$1C03			BTFSS	STATUS, C
;math.ppas,75 :: 		
$01EC	$29D2			GOTO	$-26
;math.ppas,76 :: 		
$01ED	$087B			MOVF	STACK_11, W
;math.ppas,77 :: 		
$01EE	$00F3			MOVWF	STACK_3
;math.ppas,78 :: 		
$01EF	$087A			MOVF	STACK_10, W
;math.ppas,79 :: 		
$01F0	$00F2			MOVWF	STACK_2
;math.ppas,80 :: 		
$01F1	$0879			MOVF	STACK_9, W
;math.ppas,81 :: 		
$01F2	$00F1			MOVWF	STACK_1
;math.ppas,82 :: 		
$01F3	$0878			MOVF	STACK_8, W
;math.ppas,83 :: 		
$01F4	$00F0			MOVWF	STACK_0
;math.ppas,84 :: 		
$01F5	$	math_L_1:
;math.ppas,85 :: 		
$01F5	$0008			RETURN
$01F6	$	_div_16x16_u:
$01F6	$1303			BCF	STATUS, RP1
$01F7	$1283			BCF	STATUS, RP0
;math.ppas,108 :: 		
;math.ppas,110 :: 		
$01F8	$01F8			CLRF	STACK_8
;math.ppas,111 :: 		
$01F9	$01F9			CLRF	STACK_9
;math.ppas,112 :: 		
$01FA	$3010			MOVLW	16
;math.ppas,113 :: 		
$01FB	$00FC			MOVWF	STACK_12
;math.ppas,114 :: 		
$01FC	$0D71			RLF	STACK_1, W
;math.ppas,115 :: 		
$01FD	$0DF8			RLF	STACK_8, F
;math.ppas,116 :: 		
$01FE	$0DF9			RLF	STACK_9, F
;math.ppas,117 :: 		
$01FF	$0874			MOVF	STACK_4, W
;math.ppas,118 :: 		
$0200	$02F8			SUBWF	STACK_8, F
;math.ppas,119 :: 		
$0201	$0875			MOVF	STACK_5, W
;math.ppas,120 :: 		
$0202	$1C03			BTFSS	STATUS, C
;math.ppas,121 :: 		
$0203	$0F75			INCFSZ	STACK_5, W
;math.ppas,122 :: 		
$0204	$02F9			SUBWF	STACK_9, F
;math.ppas,123 :: 		
$0205	$1803			BTFSC	STATUS, C
;math.ppas,124 :: 		
$0206	$2A0E			GOTO	$+8
;math.ppas,125 :: 		
$0207	$0874			MOVF	STACK_4, W
;math.ppas,126 :: 		
$0208	$07F8			ADDWF	STACK_8, F
;math.ppas,127 :: 		
$0209	$0875			MOVF	STACK_5, W
;math.ppas,128 :: 		
$020A	$1803			BTFSC	STATUS, C
;math.ppas,129 :: 		
$020B	$0F75			INCFSZ	STACK_5, W
;math.ppas,130 :: 		
$020C	$07F9			ADDWF	STACK_9, F
;math.ppas,131 :: 		
$020D	$1003			BCF	STATUS, C
;math.ppas,132 :: 		
$020E	$0DF0			RLF	STACK_0, F
;math.ppas,133 :: 		
$020F	$0DF1			RLF	STACK_1, F
;math.ppas,134 :: 		
$0210	$0BFC			DECFSZ	STACK_12, F
;math.ppas,135 :: 		
$0211	$29FC			GOTO	$-21
;math.ppas,136 :: 		
$0212	$	math_L_3:
;math.ppas,137 :: 		
$0212	$0008			RETURN
$00B5	$	_main:
;CodigoCalentador.pbas,81 :: 		main:
$00B5	$	_main_main:
;CodigoCalentador.pbas,83 :: 		OPTION_REG=%11000101 ' Configuracion de Puertos analogicos / digitales AN0 - AN13
$00B5	$30C5			MOVLW	197
$00B6	$1303			BCF	STATUS, RP1
$00B7	$1683			BSF	STATUS, RP0
$00B8	$0081			MOVWF	OPTION_REG
;CodigoCalentador.pbas,84 :: 		INTCON = 0
$00B9	$018B			CLRF	INTCON, 1
;CodigoCalentador.pbas,85 :: 		ANSEL =  %00000000           'REGISTRO CONFIG. O DIGITAL, 1 ANALOGICO
$00BA	$1703			BSF	STATUS, RP1
$00BB	$0188			CLRF	ANSEL, 1
;CodigoCalentador.pbas,86 :: 		ANSELH = %00000010           'REGISTRO CONFIG. O DIGITAL, 1 ANALOGICO
$00BC	$3002			MOVLW	2
$00BD	$0089			MOVWF	ANSELH
;CodigoCalentador.pbas,89 :: 		trisa  = %00000000           ' Configuracion IN/OUT PORTA
$00BE	$1303			BCF	STATUS, RP1
$00BF	$0185			CLRF	TRISA, 1
;CodigoCalentador.pbas,90 :: 		trisb  = %00001001           ' Configuracion IN/OUT PORTB
$00C0	$3009			MOVLW	9
$00C1	$0086			MOVWF	TRISB
;CodigoCalentador.pbas,91 :: 		trisc  = %10000000           ' Configuracion IN/OUT PORTC
$00C2	$3080			MOVLW	128
$00C3	$0087			MOVWF	TRISC
;CodigoCalentador.pbas,95 :: 		PORTA  = %00000000           ' Inicializacion PORTA
$00C4	$1283			BCF	STATUS, RP0
$00C5	$0185			CLRF	PORTA, 1
;CodigoCalentador.pbas,96 :: 		PORTB  = %00000000           ' Inicializacion PORTC
$00C6	$0186			CLRF	PORTB, 1
;CodigoCalentador.pbas,97 :: 		PORTC  = %00000000           ' Inicializacion PORTC
$00C7	$0187			CLRF	PORTC, 1
;CodigoCalentador.pbas,99 :: 		flag=0
$00C8	$01A3			CLRF	_flag, 1
;CodigoCalentador.pbas,100 :: 		intensidad=0
$00C9	$01A2			CLRF	_intensidad, 1
;CodigoCalentador.pbas,101 :: 		muestras=0
$00CA	$01A4			CLRF	_muestras, 1
;CodigoCalentador.pbas,102 :: 		temp_ac=0
$00CB	$01A5			CLRF	_temp_ac
$00CC	$01A6			CLRF	_temp_ac+1
;CodigoCalentador.pbas,103 :: 		temp_prom=0
$00CD	$01A7			CLRF	_temp_prom
$00CE	$01A8			CLRF	_temp_prom+1
;CodigoCalentador.pbas,104 :: 		USART_Init(9600)
$00CF	$3019			MOVLW	25
$00D0	$1683			BSF	STATUS, RP0
$00D1	$0099			MOVWF	SPBRG
$00D2	$1518			BSF	TXSTA, BRGH
$00D3	$2229			CALL	_usart_init
;CodigoCalentador.pbas,105 :: 		Delay_ms(100)
$00D4	$3082			MOVLW	130
$00D5	$00FB			MOVWF	STACK_11
$00D6	$30FF			MOVLW	255
$00D7	$00FA			MOVWF	STACK_10
$00D8	$0BFB			DECFSZ	STACK_11, F
$00D9	$28DB			GOTO	$+2
$00DA	$28DE			GOTO	$+4
$00DB	$0BFA			DECFSZ	STACK_10, F
$00DC	$28DB			GOTO	$-1
$00DD	$28D8			GOTO	$-5
$00DE	$3087			MOVLW	135
$00DF	$00FA			MOVWF	STACK_10
$00E0	$0BFA			DECFSZ	STACK_10, F
$00E1	$28E0			GOTO	$-1
$00E2	$0000			NOP
;CodigoCalentador.pbas,106 :: 		INTCON =%11010000
$00E3	$30D0			MOVLW	208
$00E4	$008B			MOVWF	INTCON
;CodigoCalentador.pbas,107 :: 		PIE1 = %00100000
$00E5	$3020			MOVLW	32
$00E6	$1683			BSF	STATUS, RP0
$00E7	$008C			MOVWF	PIE1
;CodigoCalentador.pbas,108 :: 		PIR1=0
$00E8	$1283			BCF	STATUS, RP0
$00E9	$018C			CLRF	PIR1, 1
;CodigoCalentador.pbas,109 :: 		Delay_ms(100)
$00EA	$3082			MOVLW	130
$00EB	$00FB			MOVWF	STACK_11
$00EC	$30FF			MOVLW	255
$00ED	$00FA			MOVWF	STACK_10
$00EE	$0BFB			DECFSZ	STACK_11, F
$00EF	$28F1			GOTO	$+2
$00F0	$28F4			GOTO	$+4
$00F1	$0BFA			DECFSZ	STACK_10, F
$00F2	$28F1			GOTO	$-1
$00F3	$28EE			GOTO	$-5
$00F4	$3087			MOVLW	135
$00F5	$00FA			MOVWF	STACK_10
$00F6	$0BFA			DECFSZ	STACK_10, F
$00F7	$28F6			GOTO	$-1
$00F8	$0000			NOP
;CodigoCalentador.pbas,111 :: 		i=0
$00F9	$01A1			CLRF	_i, 1
;CodigoCalentador.pbas,113 :: 		while  TRUE      ' Lazo infinito Bucle While
$00FA	$	CodigoCalentador_L_91:
;CodigoCalentador.pbas,115 :: 		do
$00FA	$	CodigoCalentador_L_95:
;CodigoCalentador.pbas,116 :: 		analogico = Adc_Read(9)
$00FA	$3009			MOVLW	9
$00FB	$00B8			MOVWF	FARG_Adc_Read
$00FC	$219A			CALL	_adc_read
$00FD	$0870			MOVF	STACK_0, 0
$00FE	$00A9			MOVWF	_analogico
$00FF	$0871			MOVF	STACK_0+1, 0
$0100	$00AA			MOVWF	_analogico+1
;CodigoCalentador.pbas,117 :: 		temperatura=(analogico*100/230) ''
$0101	$3064			MOVLW	100
$0102	$00F4			MOVWF	STACK_4
$0103	$01F5			CLRF	STACK_4+1
$0104	$21CB			CALL	_mul_16x16_u
$0105	$30E6			MOVLW	230
$0106	$00F4			MOVWF	STACK_4
$0107	$01F5			CLRF	STACK_4+1
$0108	$21F6			CALL	_div_16x16_u
$0109	$0870			MOVF	STACK_0, 0
$010A	$00AB			MOVWF	_temperatura
$010B	$0871			MOVF	STACK_0+1, 0
$010C	$00AC			MOVWF	_temperatura+1
;CodigoCalentador.pbas,118 :: 		inc(muestras)
$010D	$0AA4			INCF	_muestras, 1
;CodigoCalentador.pbas,119 :: 		Delay_ms(2)
$010E	$3003			MOVLW	3
$010F	$00FB			MOVWF	STACK_11
$0110	$30FF			MOVLW	255
$0111	$00FA			MOVWF	STACK_10
$0112	$0BFB			DECFSZ	STACK_11, F
$0113	$2915			GOTO	$+2
$0114	$2918			GOTO	$+4
$0115	$0BFA			DECFSZ	STACK_10, F
$0116	$2915			GOTO	$-1
$0117	$2912			GOTO	$-5
$0118	$3096			MOVLW	150
$0119	$00FA			MOVWF	STACK_10
$011A	$0BFA			DECFSZ	STACK_10, F
$011B	$291A			GOTO	$-1
;CodigoCalentador.pbas,120 :: 		temp_ac= temp_ac + temperatura
$011C	$0870			MOVF	STACK_0, 0
$011D	$07A5			ADDWF	_temp_ac, 1
$011E	$0871			MOVF	STACK_0+1, 0
$011F	$1803			BTFSC	STATUS, C
$0120	$3F01			ADDLW	1
$0121	$07A6			ADDWF	_temp_ac+1, 1
;CodigoCalentador.pbas,121 :: 		loop until (muestras >=200)
$0122	$	CodigoCalentador_L_96:
$0122	$30C8			MOVLW	200
$0123	$0224			SUBWF	_muestras, 0
$0124	$1C03			BTFSS	STATUS, C
$0125	$2927			GOTO	CodigoCalentador_L_98
$0126	$	CodigoCalentador_L_99:
$0126	$2928			GOTO	CodigoCalentador_L_97
$0127	$	CodigoCalentador_L_98:
$0127	$28FA			GOTO	CodigoCalentador_L_95
$0128	$	CodigoCalentador_L_97:
;CodigoCalentador.pbas,122 :: 		temp_prom = (temp_ac /200)
$0128	$30C8			MOVLW	200
$0129	$00F4			MOVWF	STACK_4
$012A	$01F5			CLRF	STACK_4+1
$012B	$0825			MOVF	_temp_ac, 0
$012C	$00F0			MOVWF	STACK_0
$012D	$0826			MOVF	_temp_ac+1, 0
$012E	$00F1			MOVWF	STACK_0+1
$012F	$21F6			CALL	_div_16x16_u
$0130	$0870			MOVF	STACK_0, 0
$0131	$00A7			MOVWF	_temp_prom
$0132	$0871			MOVF	STACK_0+1, 0
$0133	$00A8			MOVWF	_temp_prom+1
;CodigoCalentador.pbas,124 :: 		ByteToStr(temp_prom,txt)
$0134	$0870			MOVF	STACK_0, 0
$0135	$00B8			MOVWF	FARG_ByteToStr
$0136	$302D			MOVLW	_txt
$0137	$00B9			MOVWF	FARG_ByteToStr+1
$0138	$2168			CALL	_bytetostr
;CodigoCalentador.pbas,125 :: 		Usart_Write_Text("t")
$0139	$3074			MOVLW	116
$013A	$00B6			MOVWF	?main_Local_Text+0
$013B	$01B7			CLRF	?main_Local_Text+1
$013C	$3036			MOVLW	?main_Local_Text
$013D	$00B8			MOVWF	FARG_Usart_Write_Text
$013E	$2213			CALL	_usart_write_text
;CodigoCalentador.pbas,126 :: 		Usart_Write_Text(txt)
$013F	$302D			MOVLW	_txt
$0140	$00B8			MOVWF	FARG_Usart_Write_Text
$0141	$2213			CALL	_usart_write_text
;CodigoCalentador.pbas,128 :: 		muestras=0
$0142	$01A4			CLRF	_muestras, 1
;CodigoCalentador.pbas,129 :: 		temp_ac=0
$0143	$01A5			CLRF	_temp_ac
$0144	$01A6			CLRF	_temp_ac+1
;CodigoCalentador.pbas,130 :: 		temp_prom=0
$0145	$01A7			CLRF	_temp_prom
$0146	$01A8			CLRF	_temp_prom+1
;CodigoCalentador.pbas,132 :: 		Delay_ms(500)
$0147	$3003			MOVLW	3
$0148	$00FC			MOVWF	STACK_12
$0149	$30FF			MOVLW	255
$014A	$00FB			MOVWF	STACK_11
$014B	$30FF			MOVLW	255
$014C	$00FA			MOVWF	STACK_10
$014D	$0BFC			DECFSZ	STACK_12, F
$014E	$2950			GOTO	$+2
$014F	$2957			GOTO	$+8
$0150	$0BFB			DECFSZ	STACK_11, F
$0151	$2953			GOTO	$+2
$0152	$2956			GOTO	$+4
$0153	$0BFA			DECFSZ	STACK_10, F
$0154	$2953			GOTO	$-1
$0155	$2950			GOTO	$-5
$0156	$294D			GOTO	$-9
$0157	$308C			MOVLW	140
$0158	$00FB			MOVWF	STACK_11
$0159	$30FF			MOVLW	255
$015A	$00FA			MOVWF	STACK_10
$015B	$0BFB			DECFSZ	STACK_11, F
$015C	$295E			GOTO	$+2
$015D	$2961			GOTO	$+4
$015E	$0BFA			DECFSZ	STACK_10, F
$015F	$295E			GOTO	$-1
$0160	$295B			GOTO	$-5
$0161	$30A1			MOVLW	161
$0162	$00FA			MOVWF	STACK_10
$0163	$0BFA			DECFSZ	STACK_10, F
$0164	$2963			GOTO	$-1
$0165	$0000			NOP
$0166	$28FA			GOTO	CodigoCalentador_L_91
;CodigoCalentador.pbas,134 :: 		wend
$0167	$2967			GOTO	$
